improve: a hot fix for fair mine
bnb-chain/bsc pull request #1152
Opened 2022-10-28 10:23 UTC by setunapo

code: hot fix part2

code: set DelayLeftOver to 400ms, for block finalize and broadcast

fair: return when no time left

fix: init txs2Ch

fair: add txs2HotfixLoop to avoid flush txsCh on mainLoop

fair: subscribe txs event before commitTransactions

log: improve print log

### Description

add a description of your changes here...

### Rationale

tell us why we need these changes...

### Example

add an example CLI or API response...

### Changes

Notable changes: 
* add each change in a bullet point here
* ...

2022-10-30 15:24 UTC, Jolly23 commented
bad idea

2022-10-31 02:00 UTC, guagualvcha commented on miner/worker.go
> +		if reason == commitTxsNewHead || reason == commitTxsNoGas || reason == commitTxsNoTime {
why not use `reason  != commitTxsDone`?

2022-10-31 02:05 UTC, guagualvcha approved these changes

2022-10-31 02:08 UTC, guagualvcha requested changes
The transaction auction mechanism may break

2022-11-09 08:31 UTC, closed without merging