core/forkid: refactor nextForkHash
bnb-chain/bsc pull request #1177
Opened 2022-11-13 05:36 UTC by qinglin89

### Description

add a description of your changes here...

### Rationale

tell us why we need these changes...

### Example

add an example CLI or API response...

### Changes

Notable changes: 
* add each change in a bullet point here
* ...

2022-11-14 06:56 UTC, brilliant-lx approved these changes

2022-11-15 03:42 UTC, guagualvcha commented
Much better PR description is required.

2022-11-15 03:42 UTC, guagualvcha requested changes
Explain the motivation of this PR.

2022-11-17 03:41 UTC, guagualvcha approved these changes

2022-11-17 04:12 UTC, merged