update Gibbs fork height and system contract code
bnb-chain/bsc pull request #1195
Opened 2022-11-21 07:27 UTC by Pythonberg1997

### Description

Update mainnet Gibbs fork height and system contract code

### Rationale

N/A

### Example

N/A

### Changes

Notable changes: 
* Add mainnet Gibbs fork height
* Update system contract code

2022-11-21 07:28 UTC, forcodedancing submitted a review, later dismissed

2022-11-21 07:33 UTC, brilliant-lx submitted a review, later dismissed

2022-11-21 11:06 UTC, guagualvcha commented on params/config.go
>  		//TODO
remove the todo please

2022-11-21 11:06 UTC, guagualvcha commented on params/config.go
> +		GibbsBlock:          big.NewInt(23846000),
let us update to `23846001`

2022-11-21 11:16 UTC, guagualvcha commented on core/systemcontracts/upgrade.go
>  	}
For testnet hardfork, what is done is done, we can not change the byte code again, otherwise testnet can not re-sync from genesis.

2022-11-21 11:22 UTC, guagualvcha requested changes

2022-11-21 11:22 UTC, guagualvcha commented on core/systemcontracts/upgrade.go
> +				CommitUrl:    "https://github.com/bnb-chain/bsc-genesis-contract/commit/c056378abfac8695bcc6c5dde14cbdc6f151ac6d",
Any reason we dont use the latest master branch ?

2022-11-21 11:22 UTC, guagualvcha commented on core/systemcontracts/upgrade.go
> +				CommitUrl:    "https://github.com/bnb-chain/bsc-genesis-contract/commit/c056378abfac8695bcc6c5dde14cbdc6f151ac6d",
My latest compiled code can not match with yours.

2022-11-21 12:00 UTC, guagualvcha approved these changes

2022-11-22 08:28 UTC, yutianwu approved these changes

2022-11-22 08:29 UTC, merged