Bep 174 changes
bnb-chain/bsc pull request #1325
Opened 2023-02-24 14:43 UTC by emailtovamos

### Description

Required changes for [BEP174](https://github.com/bnb-chain/BEPs/pull/174)

### Rationale

tell us why we need these changes...

### Example

add an example CLI or API response...

### Changes

Notable changes: 
* add each change in a bullet point here
* ...

2023-02-28 06:27 UTC, guagualvcha commented on core/vm/contracts.go
> +	for k := range PrecompiledContractsIsBEP174 {
I think this is not necessary change.

2023-02-28 06:27 UTC, guagualvcha commented on core/vm/contracts.go
> +	PrecompiledAddressesBEP174    []common.Address
No need to define PrecompiledAddressesBEP174.

2023-02-28 06:30 UTC, guagualvcha requested changes
The PR title, description and commit info does not follow the standard, please make some change.  Example PR: https://github.com/bnb-chain/bsc/pull/1301/commits

2023-02-28 06:35 UTC, guagualvcha commented
I change the base branch to develop, so please take care of the commits in your branch.

2023-02-28 06:36 UTC, guagualvcha commented
Fix the CI check as well. Thanks.

2023-04-18 06:58 UTC, guagualvcha approved these changes

2023-04-18 06:58 UTC, brilliant-lx approved these changes

2023-04-18 06:58 UTC, merged