core/state: implement fast storage deletion (#27955)
bnb-chain/bsc pull request #1909
Opened 2023-10-08 09:20 UTC by NathanBSC

This changes implements faster post-selfdestruct iteration of storage slots for deletion, by using snapshot-storage+stacktrie to recover the trienodes to be deleted. This mechanism is only implemented for path-based schema.

For hash-based schema, the entire post-selfdestruct storage iteration is skipped, with this change, since hash-based does not actually perform deletion anyway.

---------

### Description

add a description of your changes here...

### Rationale

tell us why we need these changes...

### Example

add an example CLI or API response...

### Changes

Notable changes: 
* add each change in a bullet point here
* ...

2023-10-08 10:54 UTC, brilliant-lx requested changes
pls hold this PR, until v1.3.0 release

2023-10-08 10:56 UTC, joeylichang commented
I think we should follow the PR template spec to organize PR descriptions.
BTW, lint commur reports errors.

2023-10-13 03:00 UTC, buddh0 commented
> I think we should follow the PR template spec to organize PR descriptions. BTW, lint commur reports errors.

I will close this PR, https://github.com/bnb-chain/bsc/pull/1916 is prefered

2023-10-13 03:01 UTC, closed without merging

2023-10-13 03:01 UTC, buddh0 commented
I will close this PR, https://github.com/bnb-chain/bsc/pull/1916 is preferred