feat: recommit bid when newBidCh is empty to maximize mev reward
bnb-chain/bsc pull request #2424
Opened 2024-04-25 07:31 UTC by irrun

### Description

recommit bid when newBidCh is empty to maximize mev reward

### Rationale

tell us why we need these changes...

### Example

add an example CLI or API response...

### Changes

Notable changes: 
* add each change in a bullet point here
* ...

2024-04-25 09:03 UTC, unclezoro approved these changes

2024-04-26 07:48 UTC, Pythonberg1997 approved these changes

2024-04-26 07:50 UTC, unclezoro approved these changes

2024-04-26 08:20 UTC, unclezoro commented on miner/bid_simulator.go
>  		return
need send the best bid back to channel

2024-04-26 08:20 UTC, zzzckck commented on miner/bid_simulator.go
> +			if len(b.newBidCh) == 0 {
why need this check?

2024-04-26 08:39 UTC, zzzckck approved these changes

2024-04-26 09:02 UTC, unclezoro approved these changes

2024-04-26 12:28 UTC, unclezoro requested changes
need more changes

2024-04-26 12:37 UTC, unclezoro approved these changes

2024-04-28 03:05 UTC, zzzckck approved these changes

2024-04-28 03:05 UTC, merged