[R4R]fix:Shift panic for zero length of heads
bnb-chain/bsc pull request #870
Opened 2022-04-24 07:35 UTC by qinglin89

### Description

panic when length of heads equal to zero when `shift`

### Rationale

tell us why we need these changes...

### Example

add an example CLI or API response...

### Changes

Notable changes: 
* add each change in a bullet point here
* ...

2022-04-24 09:48 UTC, guagualvcha approved these changes

2022-04-24 10:24 UTC, guagualvcha requested changes
Will do review again.

2022-04-24 13:06 UTC, guagualvcha approved these changes

2022-04-25 02:35 UTC, Mercybudda approved these changes

2022-04-25 02:43 UTC, forcodedancing approved these changes

2022-04-25 02:47 UTC, merged