core: change ordering of txs of equal gas price from arrival time to hash
bnb-chain/bsc pull request #915
Opened 2022-05-17 19:43 UTC by ktrout1111

### Description

This pr changes the ordering of equal-gas-priced txs to be lexicographical by hash rather than by arrival time. 

### Rationale

About a year ago, version 1.10 silently merged in a change made by the Ethereum devs in a bid to mitigate spam by arb bots. They changed the sortation method of gas-equal txs from random (map key) to the time they were first seen by the node. This change has very negatively affected BSC, due to the huge number of fake spammer nodes that each bot owner now has to run in order to beat the competition. 

Before 1.10, there was indeed tx spam by arb bots on BSC, but now not only is that spam now far worse (a single bot owner very often sends **hundreds** of txs per block to grab the high value arbs), but a very high proportion of the "nodes" on the network aren't actual full nodes at all - they are fakes that only exist to flood the network with their own arb txs and censor all other txs and block data. This is all easily seen with some basic per-peer analysis of the txs that pass through eth/fetcher/tx_fetcher.go - the majority of "nodes" are in fact bad actors - so many of the syncing problems honest full node operators experience could well be influenced by the fact that only a small fraction of the MaxPeers they have set in the config are actually legit peers.

Another issue with the "first seen" tx sorting method is that we have to take it on faith that the validators are indeed ordering by the time seen and not giving preferential treatment to friends. Sorting the txs by hash would eliminate a lot of doubt, as violations of the rule would be easily spotted. Yes, they could delay "unwanted" txs by a full block, but that would look very obvious.

Sorting txs by hash would create a negative feedback loop as far as spam is concerned. As each bot hashes, the probability per second of beating the current best hash diminishes, thus therefore so does the overall rate of bot txs per arb. It would significantly reduce the block size and demands on I/O space and bandwidth, going a long way to solving the problems that have plagued full node operators for a long time.

As discussed in [269](https://github.com/bnb-chain/bsc/issues/269), [911](https://github.com/bnb-chain/bsc/issues/911).

### Changes

Notable changes: 
* add TxByPriceAndHash type
* replace TxByPriceAndTime with TxByPriceAndHash in TransactionsByPriceAndNonce

_N.B. commit is tagged "eth" by mistake - it should be "core"_

2022-05-17 23:51 UTC, lennybakkalian requested changes
### EDIT: my summary of this PR: https://github.com/bnb-chain/bsc/pull/915#issuecomment-1140497287

@ktrout1111 Can you merge my [pull request](https://github.com/ktrout1111/bsc/pull/1) where I fixed the unit tests?

2022-05-18 09:36 UTC, ktrout1111 commented
> @ktrout1111 Can you merge my https://github.com/ktrout1111/bsc/pull/1 where I fixed the unit tests?

Done. Thanks.

2022-05-18 12:52 UTC, ktrout1111 commented
@lennybakkalian Thanks for the fixes. I'm not familiar with Go's CI tools so was unaware of the need for unit testing and linting. According to GitHub's built-in checks, your changes fixed the Unit Test but not the Lint. On inspection, I found that I had added too many blank lines in transaction.go, so I removed them and recommitted. The lint now passes, but bizarrely the Unit Test is failing again on a step that appears unrelated to our changes.

When i run "make test" locally (Go 1.17.1, Ubuntu 21.04), it fails at a completely different part:

    --- FAIL: TestBlockchain/ValidBlocks/VMTests/vmPerformance/loop-add-10M.json (4.60s)
        --- FAIL: TestBlockchain/ValidBlocks/VMTests/vmPerformance/loop-add-10M.json/loop-add-10M_Berlin (0.00s)
            block_test.go:52: test without snapshotter failed: unsupported fork ordering: eulerBlock not enabled, but berlinBlock enabled at 0
            block_test.go:55: test with snapshotter failed: unsupported fork ordering: eulerBlock not enabled, but berlinBlock enabled at 0
    --- FAIL: TestBlockchain/ValidBlocks/VMTests/vmPerformance/loop-divadd-unr100-10M.json (5.81s)
        --- FAIL: TestBlockchain/ValidBlocks/VMTests/vmPerformance/loop-divadd-unr100-10M.json/loop-divadd-unr100-10M_Berlin (0.00s)
            block_test.go:52: test without snapshotter failed: unsupported fork ordering: eulerBlock not enabled, but berlinBlock enabled at 0
            block_test.go:55: test with snapshotter failed: unsupported fork ordering: eulerBlock not enabled, but berlinBlock enabled at 0
    --- FAIL: TestBlockchain/ValidBlocks/VMTests/vmPerformance/loop-divadd-10M.json (8.44s)
        --- FAIL: TestBlockchain/ValidBlocks/VMTests/vmPerformance/loop-divadd-10M.json/loop-divadd-10M_Berlin (0.00s)
            block_test.go:52: test without snapshotter failed: unsupported fork ordering: eulerBlock not enabled, but berlinBlock enabled at 0
            block_test.go:55: test with snapshotter failed: unsupported fork ordering: eulerBlock not enabled, but berlinBlock enabled at 0
    --- FAIL: TestBlockchain/ValidBlocks/bcExploitTest/SuicideIssue.json (25.79s)
        --- FAIL: TestBlockchain/ValidBlocks/bcExploitTest/SuicideIssue.json/SuicideIssue_Berlin (0.72s)
            block_test.go:52: test without snapshotter failed: unsupported fork ordering: eulerBlock not enabled, but berlinBlock enabled at 0
            block_test.go:55: test with snapshotter failed: unsupported fork ordering: eulerBlock not enabled, but berlinBlock enabled at 0

The only culprit I could think of is the change from making 5 test transactions to 10, so I changed it back locally but got the same failure at the same point in the test.

The Unit Test running on GitHub seems to be rather rickety if it is succeeding, and then failing simply by removing 2 empty lines from one source file!

2022-05-18 13:39 UTC, lennybakkalian commented
@ktrout1111 The test "TestLargeReorgTrieGC" also fails in the github pipeline, but when i run the test locally it works. weird.... ill look into it

2022-05-18 19:48 UTC, lennybakkalian commented
I am getting nowhere as this failing test works locally for me. Maybe a maintainer will be here soon.

2022-05-18 22:41 UTC, ktrout1111 commented
I tried cloning the repo again from scratch and just copy pasting our changes over the top and that caused the test to succeed locally, so I might just trash this pr in the morning and try again with a new one with all the changes in one commit.

2022-05-19 10:26 UTC, ktrout1111 commented
> I believe the failing test is not coming from us, as it also fails in another [pull request](https://github.com/bnb-chain/bsc/runs/6351410280?check_suite_focus=true#step:5:212).

I concur. It seems a bit nondeterministic, especially given that it succeeded on the previous commit. All it took to make it fail next run was the removal of 2 empty lines from a source file. I'm tempted to make a trivial change and recommit and see what happens.

2022-05-19 10:51 UTC, lennybakkalian commented
And now the test "TestProcessDiffLayer" fails. What kind of test environment is this?

2022-05-19 16:41 UTC, ktrout1111 commented
Beats me. Same error also comes up in [this PR](https://github.com/bnb-chain/bsc/pull/816). Looks like it's an issue in its own right.

2022-05-22 09:23 UTC, 48ClubSirIan commented
A different aspect: 

this way, arb bots will have 100% confidence about how txs will be ordered, thus instead of sending multiple txs, they "mine" the arbitration opportunities, which is even easier and more predictable.

remind me, what's the purpose again?

2022-05-22 10:39 UTC, ktrout1111 commented
> this way, arb bots will have 100% confidence about how txs will be ordered,

Why is this a bad thing?

> thus instead of sending multiple txs, they "mine" the arbitration opportunities,

Thus hugely reducing spam. You are against this? Why?

> which is even easier and more predictable.

What do you even mean by this? 

> remind me, what's the purpose again?

Your tone smacks of trolling. Maybe read the rationale and points raised in the linked issues before criticising a proposal you don't understand.

2022-05-22 11:12 UTC, lennybakkalian commented
I find it interesting that someone who works at a [validator finds hash based sorting bad](https://github.com/bnb-chain/bsc/issues/911). (I do not need to more)
I agree in all points with @ktrout1111 

> this way, arb bots will have 100% confidence about how txs will be ordered

Currently i can assure that arb bots have a confidence of 99%. This is due to the spamming of transactions. Also, a corrupt validator can sort transactions as he wants without this being traceable.

A big point of the blockchain is also traceability, or would you (@48ClubSirIan) disagree with me?
If someone wants to make a transaction without the arb bots finding it, they can use the "Direct-Route" of NodeReal. (Which in my opinion also sucks, because it breaks the decentralization and openness of the blockchain).

2022-05-22 12:24 UTC, ktrout1111 commented
> I find it interesting that someone who works at a https://github.com/bnb-chain/bsc/issues/911.

Very telling indeed! A real sign that at least one of the validators is indeed happy with the status quo (to the detriment of anyone running a full node). Us outsiders can of course only guess exactly how they benefit, but one obvious reason is the fees they rake in from all the spam txs, especially when some blocks are as much 50% spam txs from a single bot.

2022-05-22 16:00 UTC, 0xEcE commented
If this PR doesn't make it we all should know why...

The overall health of the network would greatly benefit from it since block space wouldn't be wasted and hardware space with it. At some point it won't be feasible to run a node for most of the people which is obviously terrible for the network.

> this way, arb bots will have 100% confidence about how txs will be ordered, thus instead of sending multiple txs, they "mine" the arbitration opportunities, which is even easier and more predictable.

How does that matter? Someone will arb it anyway with arrival time or hash sorting, the advantage is that all arb bots do their computing outside of the chain. Also, arbitrage is a good thing.

> The original change to order by arrival time made by the Eth devs would likely not have been objected to by the miners, since Eth blocks are always saturated, so spam arb txs (or the absence thereof) would not have much impact on their fee revenues. On BSC, however, that is not the case, due to the much higher, mostly vacant, block capacity. Reducing spam is good for node operators and end users, but not for validators.

Have to keep in mind that ETH gas fees are also way higher. On BSC you pay around 0.05$ which enables and incentivizes certain parties to take advantage of that.

2022-05-25 12:09 UTC, jbriaux approved these changes
This would reduce noise on BSC like a lot. So it means less storage used, less computing capacity required = more people running full nodes = good :D

2022-05-25 18:32 UTC, berktaylan commented
Good work. Any comment from devs yet ?

2022-05-25 19:34 UTC, TxByTime commented
> > This would reduce noise on BSC like a lot. So it means less storage used, less computing capacity required = more people running full nodes = good :D
> 
> That's the idea. It would drastically reduce block spam, network spam, and level the playing field for arbitrage, as well as improve transparency.

I don' think this should be merged since it does not inprove most things you mention.

Let me start by saying that the tx order by time was not "silently merged" like you are falsely stating.
There were two full blown discussion if tx time or tx hash should be used. Please refer to https://github.com/ethereum/go-ethereum/pull/21358 and https://github.com/ethereum/go-ethereum/issues/21350. The Etherum team, including some of it's long standing core members came to the conclusion that tx order by time is preferd over hash.

Why it doesn't improve block spam: 
As you can see in https://github.com/ethereum/go-ethereum/issues/21350#issuecomment-661380072 it will just lead to a sitation where bots will mine for a hash and at some point submit that tx. Now any of the other bots submits a better hash. The first bot can't replace his first tx, since the gasPrice has to remain the same. It will just submit another tx. This doesn't improve block spam. 
Block spam isn't even a problem - a failing bot tx needs only ~40.000 gas blockspace and the gasLimit is rarely reached. I personally find the spam from gamefi or nft mints more disturbing - we are already creating BAS for that.

Why is doen't improve network spam: 
Same reasons as above. 
Users are encouraged to use DisablePeerTxBroadcast flag - Network spam doesn't effect them. With this flag bot operators won't peer with you, since you don't propagate their tx and dont send them any. 
The only bots I have seen sending hundrets of tx are liquidity snipers and liquidators. But these are rare occasion that only last one or two blocks. We should be able to live with that. A single arbitrage bot is sending maybe 30 transactions for big opportunities if you include the "fake" ones.

Why it doesn't level the playing field: 
It's already possible to do arbitrage with only a single or a small amount of nodes. I haven't seen any bots that rent hundrets of VPS for that - do you have any proof for that or is this another exaggerated statement? 
If the tx were to be sorted by hash this wont be the case anymore. The big guy's will rent a lot of computing power in order to generate the best hashes. This will lead to the successful bots getting even more profit since they can afford to rent the most computing power. The smaller guy's that were able to compete for some of the opportunities won't be able to compete anymore and the bar for entry of any new player will be high and unkown. 
It will even open the door for some bas MEV that I would rather not say openly here - but it will tip the scale further to the big guys.

Why it doesn't improve transparency:
A corrupt Validator can still ignore the tx with a better hash and include a different one. They can always claim that the tx reached them after the block was already under construction.
I agree, that it will be possible to see if any validator is using a different sorting mechanism. But what do you propose should happen if they don't obey by it? The whitepaper does not mention that. If you merge this anyways against mine and the geth-team's advice, then this is something that that should be decided by governance before merging it.

As i mentioned earlier, ethereum had this disscusion already two years ago. They concluded tx by time is the best solution. We should follow their lead and keep the existing system.

2022-05-25 20:40 UTC, lennybakkalian commented
Honestly, I find it strange that suddenly developers of validators and now also someone with a new github account replies here and is against this pull request.

> There were two full blown discussion if tx time or tx hash should be used. Please refer to https://github.com/ethereum/go-ethereum/pull/21358 and https://github.com/ethereum/go-ethereum/issues/21350.

I don't think you should compare ethereum to bsc. The way it works is completely different. 


> A single arbitrage bot is sending maybe 30 transactions for big opportunities if you include the "fake" ones.

With ethereum, tx spam only makes sense if there are large MEV opportunities due to the transaction costs. with bsc, hundreds of transactions are already sent for 1-2$.
Now we have to imagine that tx sorting over the hash prevents this "wild" tx spamming. Mining a good hash is not that fast. Theoretically, a validator would only have to send its enode to an arbitrage trader, then the trader would always be prioritized. With ethereum, there are so many miners that this would not work.

> It's already possible to do arbitrage with only a single or a small amount of nodes. I haven't seen any bots that rent hundrets of VPS for that - do you have any proof for that or is this another exaggerated statement?

I have logged over a week at 3 nodes my peers, about 30% were with a duplicate ip but different publickey. i'll look it up and post it later here on github

> It's already possible to do arbitrage with only a single or a small amount of nodes. 

If you are in the business yourself, then you know very well that this is not the case ;)

> If you merge this anyways against mine and the geth-team's advice, then this is something that should be decided by governance before merging it.

Again: ethereum and bsc are different blockchains. Just because something works well for ethereum (POW) doesn't mean it will work well for bsc (PoSA).

2022-05-25 20:46 UTC, MrSonicMaster commented
I don't personally see why TxByTime's account creation time matters - every point he brings up is valid. Such a change will only centralize MEV and support "the rich get richer." Those with the most hashpower will continue to dominate, smaller fish will get crushed, validators will still be able to order however they want without anyone knowing, and spam will still be a problem.

> Now we have to imagine that tx sorting over the hash prevents this "wild" tx spamming. Mining a good hash is not that fast.

Mining a good hash that's at least 1 bit closer won't take long, and bots will likely continue to spam new txns for every extra bit accuracy they get.

2022-05-25 20:49 UTC, lennybakkalian commented
> will still be able to order however they want without anyone knowing, and spam will still be a problem.

can you explain why?

2022-05-25 20:51 UTC, henopied commented
In addition to the comments by @TxByTime, I would like to add that this will likely create a dynamic similar to [Priority Gas Auctions](https://arxiv.org/abs/1904.05234) but instead with bot operators sending each hash with an improved bit-level similarity. This dynamic could result in essentially one transaction sent per operator per improved bit of similarity or even per node, as you seem to be observing.
However, I have greater concerns for users of BSC. These changes will open the door to predatory deterministic frontrunning and sandwich operations. Currently, sandwich operators have to contend with high competition on the backrun due to latency competition and uncertain p2p networking conditions. This uncertainty creates a risk of your frontrun transaction not landing correctly or not being correctly paired with a backrun transaction. If an operator can virtually guarantee their position by having a hashpower advantage, they will surely convert into a sandwiching operation as the risk of uncertainty is greatly diminished. We will see centralization of MEV with these changes as hashpower infrastructure becomes the main competitive factor. These changes seem to benefit established players with strong resources to buy hashpower infrastructure while adding additional revenue through new, predatory MEV opportunities.
A better solution should directly target the symptoms you complain of: unproductive nodes. If a peer is not contributing significant activity or responding to requests for data, a heuristic could kick them and look for better peers. This solution would directly address the concerns of unproductive nodes interfering with syncing without creating predatory and centralized MEV.

2022-05-25 20:58 UTC, lennybakkalian commented
> These changes will open the door to predatory deterministic frontrunning and sandwich operations.

What does that have to do with it? to frontrun a tx, you simply pay more gasPrice and to backrun it, you send it on with a small delay? Such MEV transactions are currently always sandwitched anyway. This PR changes nothing except to make the sequence of the transactions traceable.

Isn't it enough proof that members of validators [are against this pull request with strange reasons](https://github.com/bnb-chain/bsc/pull/915#issuecomment-1133854329)?

2022-05-25 21:01 UTC, 0xEcE commented
> Why it doesn't improve block spam: As you can see in [ethereum/go-ethereum#21350 (comment)](https://github.com/ethereum/go-ethereum/issues/21350#issuecomment-661380072) it will just lead to a situation where bots will mine for a hash and at some point submit that tx. Now any of the other bots submits a better hash. The first bot can't replace his first tx, since the gasPrice has to remain the same. It will just submit another tx. This doesn't improve block spam. 

This statement is simply wrong. Blocks on BSC are not as long as on ETH, limiting the time to generate those "better hashes". Since this time limit is in place, bot operators have limited time to try out hashes, resulting in less spam.

> Bot operators can't be certain about their tx placement. Their competition can just send them a "fake" transaction with same nonce and bad hash - they will never know the good hash. So they will keep mining and still spam when they find a better hash.

Fake transactions is not a thing either, because they would simply fail the sanity checks.

>Block spam isn't even a problem - a failing bot tx needs only ~40.000 gas blockspace and the gasLimit is rarely reached. I personally find the spam from gamefi or nft mints more disturbing - we are already creating BAS for that.

Not all transactions use around 40.000 gas. They range between 30k-200k and they definitely add up because there are more than just a single bot operator or users that spam the network. 

> Why is doen't improve network spam: Same reasons as above. Users are encouraged to use DisablePeerTxBroadcast flag - Network spam doesn't effect them. With this flag bot operators won't peer with you, since you don't propagate their tx and dont send them any. The only bots I have seen sending hundrets of tx are liquidity snipers and liquidators. But these are rare occasion that only last one or two blocks. We should be able to live with that. A single arbitrage bot is sending maybe 30 transactions for big opportunities if you include the "fake" ones.

The occasions you mentioned definitely last much longer than just "1-2 blocks". There were times BSC was barely usable due to high spam with blocks having 1500-2000 transactions each. Hash sorting would eliminate the need to spam and try to backrun with hundreds of thousands of transactions over a longer period of time.

> Why it doesn't level the playing field: It's already possible to do arbitrage with only a single or a small amount of nodes. I haven't seen any bots that rent hundrets of VPS for that - do you have any proof for that or is this another exaggerated statement? 

Arbitrage is a highly competetive space and people definitely go to that extent to beat others.

> If the tx were to be sorted by hash this won't be the case anymore. The big guy's will rent a lot of computing power in order to generate the best hashes. This will lead to the successful bots getting even more profit since they can afford to rent the most computing power. The smaller guy's that were able to compete for some of the opportunities won't be able to compete anymore and the bar for entry of any new player will be high and unkown. 

That is not the case either because the best players win no matter what, new players won't be able to win against them in both scenarios. The one with the lowest latency will win and guess what - the rich ones will just buy the best hardware to get the lowest latency, same goes with computing power.


> Why it doesn't improve transparency: A corrupt Validator can still ignore the tx with a better hash and include a different one. They can always claim that the tx reached them after the block was already under construction. I agree, that it will be possible to see if any validator is using a different sorting mechanism. But what do you propose should happen if they don't obey by it? The whitepaper does not mention that. 

It does improve transparency. Right now nobody can tell what validators are doing except some corrupt and obvious ones (like buying cheap gas tokens). It would be noticable if certain contracts or EOA's are consistent during blocks mined by specific validators. Of course they could censor other transactions but that shouldn't work in the long run because they have to generate a "decent" hash themselves and hide this consistency which would be very hard.

> If you merge this anyways against mine and the geth-team's advice, then this is something that should be decided by governance before merging it. This change might be small, but has a huge impact.

ETH tx sorting wasn't done with a governance vote, so I don't see reason this should be. Also since many validators are against that idea (I wonder why :)) the outcome would be as rigged as the revival of Terra.

2022-05-25 21:22 UTC, MrSonicMaster commented
> > Such a change will only centralize MEV
> 
> can you explain why?

Think about it, people who have already been successful with MEV will have the infrastructure/money to get high hashpower, and as such will continue to dominate. Those who struck a deal with validators will also still win, as the validators can still chose to ignore others txns and insert their own. The barrier of entry will become too great for new players.

2022-05-25 21:25 UTC, 0xEcE commented
> Think about it, people who have already been successful with MEV will have the infrastructure/money to get high hashpower, and as such will continue to dominate.

As I mentioned before, this will be the case no matter what. 
- Random ordering: more money to spam
- Arrival time ordering: more money to buy lower latency
- Hash sorting: more money to buy computing power

> Those who struck a deal with validators will also still win, as the validators can still chose to ignore others txns and insert their own. The barrier of entry will become too great for new players.

Behaviour like this will be easier to detect with hash sorting, instead of arrival time / random sorting.

2022-05-25 21:32 UTC, henopied commented
> What does that have to do with it? to frontrun a tx, you simply pay more gasPrice and to backrun it, you send it on with a small delay?
With the proposed ordering an operator can directly frontrun at an equal gas cost without many tx of the target transaction's gas cost between that may interfere with your opportunity. Additionally, winning a backrun is not as trivial as sending a tx with a short delay. There is currently a significant risk to attempting a sandwich opportunity as it is not atomic and is uncertain due to the current ordering scheme.

2022-05-25 21:40 UTC, 0xEcE commented
> With the proposed ordering an operator can directly frontrun at an equal gas cost without many tx of the target transaction's gas cost between that may interfere with your opportunity. Additionally, winning a backrun is not as trivial as sending a tx with a short delay.

If people or users are worried about slippage and getting sandwiched, they can resort to different solutions such as
- Direct Route
- Low Slippage
- 0 Slippage Protocols
With that in mind users have the opportunity to counteract against getting frontrun.

> There is currently a significant risk to attempting a sandwich opportunity as it is not atomic and is uncertain due to the current ordering scheme.

This risk will not be eliminated since it is not guaranteed that their transaction will be executed in the same block.

2022-05-25 21:47 UTC, MrSonicMaster commented
> > Think about it, people who have already been successful with MEV will have the infrastructure/money to get high hashpower, and as such will continue to dominate.
> 
> As I mentioned before, this will be the case no matter what.
> 
> * Random ordering: more money to spam
> * Arrival time ordering: more money to buy lower latency
> * Hash sorting: more money to buy computing power
> 
> > Those who struck a deal with validators will also still win, as the validators can still chose to ignore others txns and insert their own. The barrier of entry will become too great for new players.
> 

Yes, of course money will play a role no matter what. I'll quickly mention that random ordering is pretty clearly the worst option (it only causes more spam with barely any loss to the bot operators) so I don't think it needs further discussion. As for latency, it can only be improved so much by spending more money/running more nodes. Bot operators can simply buy a few aws instances and get comparable latency to the top operators. The issue is that mass amounts of money will always win greater hashpower.

> Behaviour like this will be easier to detect with hash sorting, instead of arrival time / random sorting.

I disagree that it would make it any easier to detect. Validators can still compute a hash that would make things order the correct way while censoring whatever transactions they want to. They'd have plausible deniability about whether the 'better hash' transaction ever made it to them in time. Regardless, this point is not the largest concern as just about all proposals have this issue (this pr would not improve or hurt this aspect).

> A better solution should directly target the symptoms you complain of: unproductive nodes. If a peer is not contributing significant activity or responding to requests for data, a heuristic could kick them and look for better peers. This solution would directly address the concerns of unproductive nodes interfering with syncing without creating predatory and centralized MEV.

I believe that this is the best proposition so far.

2022-05-25 22:12 UTC, TxByTime commented
[smartins](https://github.com/smartins)
>There was none on BSC. We simply found out about it after the fact (new build released with this different block ordering mechanics).

Why should there have been one? It was disscussed on eth already. The problem, issues and the solution are the same.

> Do you have any proof that it's possible to arbitrage using single or a small amount of nodes? Are you referring to BSC right, not ETH?

I run some bots on bsc with a small amount of nodes.

[lennybakkalian](https://github.com/lennybakkalian)
>Honestly, I find it strange that suddenly developers of validators and now also someone with a new github account replies here and is against this pull request. https://github.com/bnb-chain/bsc/issues/911

Before my comment only two people commented this PR and no one pointed out the negative sides of it that were already discussed during the PR on Eth. Not everyone that disagrees with you is against you. I think I have made it clear that this PR will hurt you more than it helps.

>I don't think you should compare ethereum to bsc. The way it works is completely different.

They run both on the same software. They are not that different. Most of the problem they mentioned during the tx time vs tx order discussion also apply here.

[0xEcE](https://github.com/0xEcE)
>This statement is simply wrong. Blocks on BSC are not as long as on ETH, limiting the time to generate those "better hashes". 
Since this time limit is in place, bot operators have limited time to try out hashes, resulting in less spam.

3s is a lot of time for computers. You should watch a PGA of some Sandwich bots. After this PR every backrun will be a PGA for the best hash - with the difference that every spam tx during the PGA lands on the chain.

>Fake transactions is not a thing either, because they would simply fail the sanity checks.

They are a thing. [ktrout1111](https://github.com/ktrout1111) mentioned them already.

>Not all transactions use around 40.000 gas. They range between 30k-200k and they definitely add up because there are more 
than just a single bot operator or users that spam the network.

I was talking about reverting txs. those are like 40.000

>The occasions you mentioned definitely last much longer than just "1-2 blocks". There were times BSC was barely usable due to high spam with blocks having 1500-2000 transactions each. Hash sorting would eliminate the need to spam and try to backrun with hundreds of thousands of transactions over a longer period of time.

If its a backrun it can only last a few blocks. I remember some nft mint where the chain was unusable for hours. We don't discuss any changes because of that. During high volatitly there will be a lot of opportunities - this will lead to congestion - no way to prevent that.

>That is not the case either because the best players win no matter what, new players won't be able to win against them in both scenarios. The one with the lowest latency will win and guess what - the rich ones will just buy the best hardware to get the lowest latency, same goes with computing power.

Currenly anyone can buy a AWS Server and compete atleast for some opportunities. After this PR the barrier to entry will be renting a small mining farm.

>ETH tx sorting wasn't done with a governance vote, so I don't see reason this should be. Also since many validators are against that idea (I wonder why :)) the outcome would be as rigged as the fork proposal of Terra.

governance vote was refering to implementing slashling for unfair tx order.

[MrSonicMaster](https://github.com/MrSonicMaster)
>Yes, of course money will play a role no matter what. I'll quickly mention that random ordering is pretty clearly the worst option (it only causes more spam with barely any loss to the bot operators) so I don't think it needs further discussion. As for latency, it can only be improved so much by spending more money/running more nodes. Bot operators can simply buy a few aws instances and get comparable latency to the top operators. The issue is that mass amounts of money will always win greater hashpower.

Yes random is the worst - just look at Polygon.
I think the goal of this PR should be clear. If its to level the Playingfield for MEV its the wrong way. Currenly anyone can buy a AWS Server and compete atleast for some opportunities. After this PR the barrier to entry will be renting a small mining farm or even worse.
For the other issues like fake nodes, cheap gasPrices there shuld be better solutions as changing the tx order mechanics.

2022-05-25 22:17 UTC, lennybakkalian commented
Let's just compare all the points.
I will expand this table if i find more arguments here

|                                           | Hash based sorting                                                                                                                                                                     | ArrivalTime based sorting                                                                                                                     |
|-------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|
| **Pending Tx Spam (same nonce/gasPrice)** | would not be practicable because it would take longer to find a better hash before the tx reached the validator                                                                        | tx with different hash can be spammed immediately over multiple p2p nodes in the network                                                      |
| **Unique Tx Spam**                        | instead of pending tx spam, unique tx are then sent as soon as a better hash is found. However, the spam would decrease because these transactions cost money, unlike pending tx spam. | different addresses try to execute an arb trade on the same contract. (probably also via several nodes)                                       |
| **MEV participants**                      | buy more servers to get more hash power                                                                                                                                                | buy more nodes to keep delay as short as possible                                                                                             |
| **MEV opportunities**                     | more accurate mev transactions                                                                                                                                                         | inaccurate mev txs. but due to the fact that there are so many mev participants, every MEV tx is sandwiched, frontrunned or backrunned anyway |
| **corrupt validators**                    | txs are censored by the competition                                                                                                                                                    | can sort the way they want                                                                                                                    |

2022-05-25 22:55 UTC, ktrout1111 commented
@TxByTime 

Given that you claim to run a profitable arb platform using only a handful of nodes under the current climate, which I know for a fact from experience is impossible, and given that you are hiding behind a throwaway account, I suspect that you are being disingenuous with these patently false claims. However, in my replies below, I will take them at face value:

> Let me start by saying that the tx order by time was not "silently merged" like you are falsely stating.

I mean it was silently merged by the BSC devs. I'm aware of the debate the Eth devs had. No such debate was held by the BSC devs (at least not publicly) that weighed up the benefits and how the change would affect BSC. And the debate by the Eth devs was far from unanimous in favour of time based sorting. Hash based sorting (both tx and address) were proferred as a solution by many.

> Now any of the other bots submits a better hash. The first bot can't replace his first tx, since the gasPrice has to remain the same. It will just submit another tx. This doesn't improve block spam.

You don't even present an argument here, but you are essentially relying what the Eth dev hendrikhofstadt said on the matter in the thread you linked to make your non argument for you. He said:

> I think that hash ordering is not a solution as bots will still spam better hashes as they mine them. They cannot rely on what they see in their local mempool to determine whether they will win with their last submitted hash (especially since the new 2 stage propagation protocol).

Let's deconstruct this assertion and see why it is wrong. Hendrik is assuming that under a hash-sorted regime, bot operators would take a mere hash (received via Notify() in the tx_fetcher rather than Enqueue()) as gospel. This would be highly idiotic of the bot operator. If they acted on this they would either sit there never attempting a single arb because they believe someone's fake amazing hash or spamming themselves into the poor house because they know it's fake and have no frame of reference so have to guess. Darwin would quickly show such players the door. 

Since you claim to be running a successful bot under the current system, that means you are intimately familiar with tx_fetcher.go and have ripped out all that timer wait queue crap and replaced it with something that grabs the full tx body within a couple of milliseconds of receiving the hash. The full tx body can then be validated (you'd have to be running a full node, of course) to prove that it is real (or not). Thus, any argument that sort-by-hash still results in a lot of spam collapses. Period. The 2 stage propagation protocol is a minor hurdle, and has to be overcome by bot operators regardless of the sort order.

So, given the FACT that a sane bot operator CAN rely on whats in their "mempool", provided they take the obvious precautions that are very similar to the ones taken under the current system, they always knows what the best hash made by anyone for a given arb is (or was 200ms ago, due to latency). Assuming constant hash power for the duration of an arb window (up to 3 seconds), the probability of anyone spamming another transaction decreases monotonically with time. This fact should be immediately obvious to anyone, but if it's still a mystery, I will draw a diagram with some basic math tomorrow. It's really simple.

> Bot operators can't be certain about their tx placement. Their competition can just send them a "fake" transaction with same nonce and bad hash - they will never know the good hash

False. See above.

>It's already possible to do arbitrage with only a single or a small amount of nodes.

No, it isn't. I wasted a lot of time learning that. Unless of course you have some privileged black book of enodes?

>  I haven't seen any bots that rent hundreds of VPS for that - do you have any proof for that or is this another exaggerated statement?

How could I prove that? I could provide logs of my hacked tx_fetcher if I still had them, but such things can be faked. If you are genuinely interested, it's very easy to mod tx_fetcher to learn that a single entity is running hundreds (not an exaggeration) of nodes. This is how it was back in Jan/Feb anyway, it's probably a lot more now. All the proof is whizzing around the network all the time. It's not hidden.

to be continued..

2022-05-25 23:02 UTC, MrSonicMaster commented
@lennybakkalian I edited your table. I feel as though its a bit more accurate, though I'd love to hear your thoughts on it.

           | Hash based sorting | ArrivalTime based sorting
-------- | -------------------------- | ---------------------------------- 
Pending Tx Spam (same nonce/gasPrice) | would not be practical because it would take longer to find a better hash before the tx reached the validator | will generate one txn per opportunity and send it to the network from each of their nodes | 
Unique Tx Spam | instead of pending tx spam, unique tx are then sent as soon as a better hash is found. However, the spam would be more harmful to the network as txns of incrementally better hashes would land. | wont happen, because they can just use the same account & nonce on multiple nodes and not have to pay for multiple txns to land when only one will benefit them - still can take advantage of latency benefit of multiple nodes
MEV participants | whoever has most $$ or strikes a deal with corrupt validators will win - more \$ = more hashpower = higher win rate (basically centralizes MEV) | buy more nodes to keep delay as short as possible. there's an upper bound to how many extra nodes will be beneficial though. around 3-4 strategically placed nodes will suffice to compete with big players. (more nodes only hurts the network if they are "fake" nodes/edited to not reply with valid data upon request/not prop. others txns etc. which is unfortunately what happens as they are lighter/easier to run.) (also deal with corrupt validator applies here)
MEV opportunities | more opportunity for predatory frontrunning | frontrunning is risky, many txn of same gas price = not guaranteed to perfectly sandwich. 
corrupt validators | can still sort the way they want - can compute first hash that is good enough to order stuff correctly while censoring the "better hash" txns received from others - has plausible deniability that "better hash" txn ever made it to them (pr does not help with transparency/validator corruption) | can sort the way they want

I don't deny that these useless spam nodes are a big issue and something must be done about it, but i don't think this PR is the answer. 
A better solution is to add a heuristic for kicking useless nodes. It would force the MEV people to stop spinning up these fake nodes only that spam txns over p2p and instead spin up actual nodes, which would benefit the network.

2022-05-25 23:23 UTC, lennybakkalian commented
> A better solution is to add a heuristic for kicking useless nodes. It would force the MEV people to stop spinning up these fake nodes only that spam txns over p2p and instead spin up actual nodes, which would benefit the network.

And how would that turn out? node is kicked after x minutes if it does not send any pending transactions? Okey, then the fake nodes forward 1 tx every second and the node has already survived this check. We should not try to detect and eliminate fake nodes, but destroy the incentive to run fake nodes, otherwise it ends in a cat and mouse game.

2022-05-25 23:54 UTC, lennybakkalian commented
> -if the remote node is synced, and they repeatedly refuse to reply with valid data on request then kick them & put them in timeout for X amount of time. They don't need help syncing, and aren't helping us at all so why stay connected. Perhaps also a few extra checks could help, like monitoring txns & blocks from them. This forces the "spam bots" to serve data that benefits the network if they actually want us to propagate their txns, and stops the issue where half of peoples peers are not helping them to sync.

then the fake node simply sends the request to another node and returns the result. I think you can never 100% detect such fake nodes. Also: How do you know if this node has this pending tx? Not every node gets every pending tx.

Currently every node forwards the pending tx hashes and answers with the full tx body on request. But I haven't understood exactly how your example should work in the real world?

2022-05-26 00:19 UTC, MrSonicMaster commented
> then the fake node simply sends the request to another node and returns the result. I think you can never 100% detect such fake nodes. Also: How do you know if this node has this requested pending tx? Not every node gets every pending tx in time.

The point of that idea isn't to 100% detect fake nodes, but to modify the 'useless peer' kick geth has to enforce benefit to the network. Yes, not everyone has every bit of data, but they'll either have something useful to you or they wont. If they aren't useful, kick them & put them in timeout. 

> Currently every node forwards the pending tx hashes and answers with the full tx body on request. But I haven't understood exactly how your example should work in the real world?

As far as i'm aware, your node will only ever request pending txn from peer if the peer announces that it has it via PooledTransactionHashes msg.

I'll also point that the OPs motivation for this PR was spiked by an analysis of the p2p network: 

> they are fakes that only exist to flood the network with their own arb txs and censor all other txs and block data. This is all easily seen with some basic per-peer analysis of the txs that pass through eth/fetcher/tx_fetcher.go - the majority of "nodes" are in fact bad actors - so many of the syncing problems honest full node operators experience could well be influenced by the fact that only a small fraction of the MaxPeers they have set in the config are actually legit peers.

An adaptation of his detections being added as a heuristic check to geth could help to weed out or at least limit the spam that these bots are capable of getting away with. Given all the downsides this PR could cause and the lack of upsides, I still stand by my statement that this PR is not the way to go.

2022-05-26 01:18 UTC, 0xEcE commented
> > then the fake node simply sends the request to another node and returns the result. I think you can never 100% detect such fake nodes. Also: How do you know if this node has this requested pending tx? Not every node gets every pending tx in time.
> 
> The point of that idea isn't to 100% detect fake nodes, but to modify the 'useless peer' kick geth has to enforce benefit to the network. Yes, not everyone has every bit of data, but they'll either have something useful to you or they wont. If they aren't useful, kick them & put them in timeout.
> 
> > Currently every node forwards the pending tx hashes and answers with the full tx body on request. But I haven't understood exactly how your example should work in the real world?
> 
> As far as i'm aware, your node will only ever request pending txn from peer if the peer announces that it has it via PooledTransactionHashes msg.
> 
> I'll also point that the OPs motivation for this PR was spiked by an analysis of the p2p network:
> 
> > they are fakes that only exist to flood the network with their own arb txs and censor all other txs and block data. This is all easily seen with some basic per-peer analysis of the txs that pass through eth/fetcher/tx_fetcher.go - the majority of "nodes" are in fact bad actors - so many of the syncing problems honest full node operators experience could well be influenced by the fact that only a small fraction of the MaxPeers they have set in the config are actually legit peers.
> 
> An adaptation of his detections being added as a heuristic check to geth could help to weed out or at least limit the spam that these bots are capable of getting away with. Given all the downsides this PR could cause and the lack of upsides, I still stand by my statement that this PR is not the way to go.

Given the fact that the only arguments against that PR are "it's worse" without really stating why or giving plausible explanation aswell as "rich people will have more power" or "entry barrier for newbs" suggests that the upsides are indeed worth going for.

2022-05-26 02:12 UTC, MrSonicMaster commented
> Given the fact that the only arguments against that PR are "it's worse" without really stating why or giving plausible explanation aswell as "rich people will have more power" or "entry barrier for newbs" suggests that the upsides are indeed worth going for.

I'm not sure that you've been following closely enough, there have been many reasons given for why it's bad.

2022-05-26 10:45 UTC, ktrout1111 commented
@smartins 

> I know for a fact that the fastest "bots" use hundreds of nodes (heavily modified) on many different locations. Now, I can't and wont reveal private details on a public forum but this was revealed directly by a bot operator.

Yep, this is easily verified by anyone who runs a modified tx_fetcher and analyses the data they receive. It's not rocket science.

@lennybakkalian 

> Honestly, I find it strange that suddenly developers of validators and now also someone with a new github account replies here and is against this pull request

This thread was dead for days then suddenly a bunch of antis all turn up within a few minutes. Reeks of brigading.

> I don't personally see why TxByTime's account creation time matters - every point he brings up is valid. 

@MrSonicMaster 

No, every point he brings up is NOT valid. Most of them aren't even points, just baseless claims built on provably false statements. He doesn't provide an argument or model, or any quantitative analysis whatsoever. Perhaps you could fill in the blanks on his behalf?

> Such a change will only centralize MEV and support "the rich get richer."

Hahaha.. this is a joke, right? In case you weren't already aware, MEV is already EXTREMELY centralised due to the current sorting method. As in, a single entity or individual scoops up most of the MEV. See my comment [here](https://github.com/bnb-chain/bsc/issues/879#issuecomment-1117076895).

Now, I want to really focus on this argument, and debunk it. Like most of the other claims that have been made, they haven't been backed up with any modelling or metrics whatsoever. The actual truth is that sorting by time centralises MEV in the hands of a tiny minority worse than any other scheme. Here's why. It has been correctly pointed out by both sides that under any sorting rule, the bigger players will dominate, due to having more wherewithal for VMs. But there is a key difference - under the current sorting by time, return is not **directly** proportional to investment because of fee expenditure. Even if we assume that a bot operator's chance of winning an arb is proportional to how many nodes they are running, this share of the revenue gets completely wiped out by tx fees for the smaller players. To win overall, one has to have lots of nodes _and_ spam a lot. It's a multiplier effect that works massively in favour of the big players and crushes the small ones. How's that for centralisation? Don't believe me? Look at the blockchain. Completely dominated by one player hiding behind 4 contracts. One tx does not equal "one vote" under the current system.

Compare this to sorting by hash. Even if the Big Whale has 50% of the total hash power, and Little Fish only has 1%, then Little Fish can be confident that amortised over time he will get roughly 1/50th of the **net** profit his competitor does, because the fee drawdown is roughly proportionally lower for Little Fish. Almost every time he "loses" an arb he doesn't send a single tx, because he can see from the mempool that the current best hash in the pool is better than his best local hash. Yes, latency is an X factor here - the best hash in any given node's mempool could be stale by up to 300ms, and could lead to additional speculative spam, but even the probability of this diminishes monotonically per bot operator over time.

2022-05-26 11:03 UTC, ktrout1111 commented
@TxByTime 

> Users are encouraged to use DisablePeerTxBroadcast flag - Network spam doesn't effect them.

This is a valid point, kinda. FWIW, I think the introduction of this "feature" was an awful decision. What kind of P2P system has a "feature" to disable gossip? As I recall, this feature was created as an emergency compromise when the network was in real crisis, with a lot of people unable to sync a full node. If they had instead taken steps to reduce the spam instead of cater for it, there might not have been a need to allow nodes to not be nodes.

> The only bots I have seen sending hundrets of tx are liquidity snipers and liquidators.

You clearly aren't looking then.

> This will lead to the successful bots getting even more profit since they can afford to rent the most computing power. 

See my above comment to @MrSonicMaster that explains why the opposite of what you are saying would occur.

> The smaller guy's that were able to compete for some of the opportunities won't be able to compete anymore

This has already been the case for a very long time, due to the sorting by time.

> Why it doesn't reduce the "fake" nodes:
Bot operators will still have all these nodes. If they get a tx a couple of ms faster or can send it a little later it gives them more time to mine for hashes. They won't give up this edge if they already have it.

OK, this is a valid point, to an extent, but let me analyse this, since you never provide any analysis in your "arguments". You are right to say that bot operators would still benefit from a somewhat distributed model so as to begin mining hashes as soon as possible to get an extra edge. However, this would not require hundreds of tiny VMs as is currently the case. A much smaller number of large VMs would make more sense. This is because both the sources of mark txs and sinks (validators) are clustered in a handful of server farms. Again, I suspect you are being disingenuous since if you are indeed running a successful bot then you already know all of this.

> A corrupt Validator can still ignore the tx with a better hash and include a different one. They can always claim that the tx reached them after the block was already under construction.

This would be much easier to detect than under the current system and bot operators would easily learn which validators to "sit out".

2022-05-26 11:12 UTC, ktrout1111 commented
@lennybakkalian 

> I have logged over a week at 3 nodes my peers, about 30% were with a duplicate ip but different publickey. i'll look it up and post it later here on github

FYI, this is not the way to detect the identity of a bot node owner. The vast majority of bot nodes are on distinct IPs, although they are very heavily clustered on certain geographical regions/data centres. The way to do it is to listen to the full boded txs arriving at Enqueue(). Bot spam is easy to spot because they never bother with Notify() as that is too slow. They send an array of 2 full txs - the mark tx at index 0, and their arb at index 1. So the first filter is len(txs) == 2, the next filter is the first 4 bytes of the input data of tx 0 matches the funcSig of a Uniswap Router swap function. If this filter is passed, you then just look at the receive address of tx 1 to see the arb contract. From here, it's very easy to see that hundreds of nodes always spam to the same contract or set of contracts. So, @TxByTime, that's how I know...

2022-05-26 11:16 UTC, lennybakkalian commented
@ktrout1111 thanks for the explanation, i will have a look later. Was just surprised that there are so many enodes with the same ip.

> This thread was dead for days then suddenly a bunch of antis all turn up within a few minutes.

May be because I had asked on the bsc discord for a mod who looks at the PR.

> Compare this to sorting by hash. Even if the Big Whale has 50% of the total hash power, and Little Fish only has 1%

The fish can also pre mine hashes and send them out on big deals. You just have to be inventive to get something like this done. The big people (who want to have every trade) have to generate hashes every second, while the small ones concentrate on individual trades with their pre mined the hash. That would be fair, because everyone is rewarded equally depending on how much hashpower they have.

@MrSonicMaster 
> but to modify the 'useless peer' kick geth has to enforce benefit to the network. Yes, not everyone has every bit of data, but they'll either have something useful to you or they wont. If they aren't useful, kick them & put them in timeout.

Recognizing fake nodes will not work. There will always be a way to avoid being recognized as a useless peer. I think you are steering in the wrong direction here, as i said our goal should not be to mark fake nodes as useless, but to eliminate useless nodes from the world. And that is only possible if you take away the incentive to operate such a node.

2022-05-26 15:49 UTC, TxByTime commented
@[ktrout1111](https://github.com/ktrout1111)
>This thread was dead for days then suddenly a bunch of antis all turn up within a few minutes. Reeks of brigading.

Like [lennybakkalian](https://github.com/lennybakkalian) said I saw on discord that this was about to be "silently merged" by two persons that try to build a MEV bot without discussing the negative sides off it.

>>You are claiming things as facts that are just not facts

>No, this is what you are doing. You have nothing to back up your claim.

Sorry I did not quote the statement i was refering to:

>Given that you claim to run a profitable arb platform using only a handful of nodes under the current climate, which I know for a fact from experience is impossible

This is what you claim for a fact that is just not a fact. Just because you are unable to do something doesn't make it impossible. MEV is much more than just standard Pancakeswap arbitrage. For some reason you only see that and refuse to look beyond it at the bigger Picture where the small guy's currently can make a profit. But there is no free lunch. You still have to work hard for it, broaden your horizion and maybe explore non atomic strategies.

>Hahaha.. this is a joke, right? In case you weren't already aware, MEV is already EXTREMELY centralised due to the current sorting method. As in, a single entity or individual scoops up most of the MEV. See my comment https://github.com/bnb-chain/bsc/issues/879#issuecomment-1117076895.

You really should stop using MEV for this type of arbitrage. Like I said above MEV is more than this. This single entity you mention is not even picking up most of the Pancakeswap arbitrage. It has atleast two competitors and is currently not even the best on most days. Hint: look for 0x1de9c881 signatures.

>OK, this is a valid point, to an extent, but let me analyse this, since you never provide any analysis in your "arguments". You are right to say that bot operators would still benefit from a somewhat distributed model so as to begin mining hashes as soon as possible to get an extra edge. However, this would not require hundreds of tiny VMs as is currently the case. A much smaller number of large VMs would make more sense. This is because both the sources of mark txs and sinks (validators) are clustered in a handful of server farms. Again, I suspect you are being disingenuous since if you are indeed running a successful bot then you already know all of this.

Why should they replace their infra? They run another bot that competes in PGA's - they won't replace their infra. They need that to win there. Since this PR won't get rid of PGA's it won't remove these "fake" nodes.
My other point also still stands: They will still use it if it means they can get a tx a few ms faster or can send it a few ms later to a validator. At some Point it will be cheapter to run these "fake" nodes as buying more hashpower.

There will be BAS to reduce nft and gamefi spam so no need to discuss that here.

>There should be fewer spam txs than there are currently. I don't know anything about PGAs, maybe they would be an even better solution.

Let me tell you about PGA's then: bot1 submits a tx. Now bot2 also want to submit a tx for the same opportunity and uses a higher gasPrice. Bot1 sees that also raises the gasPrice because of that. This is repeated until the cost are equal to profit or the block is mined.
They cause a similar amount of networkspam and tx that should confuse the competition. They just never land in a block. Sometimes there is a replacement tx every 10ms for 3s with multiple bots competing. This happens for a lot of different MEV types: CEX-DEX, Crosschain, Sandwich, and some other advanted stategys.
You can not do a PGA for a backrun - you need the same gasPrice for a backrun. A PGA requires increasing it.

>Whoa, this is a complete misrepresentation of what I said. 

Maybe fake txs was a bad word choice by me. They are exactly what you say: Real tx to confuse the competition that will never get mined.

Summary:
Fake nodes: Won't be reduced, since they still need these for their PGA strategies.
When its cheaper to rent fake nodes in order to get a tx faster than to rent more hashpower they will also do that - Principle of least effort

Tx Spam: It will still happen until all Validators have updated their nodes. This might take some time, because some Validatos are still using v1.1.5. After that it will decreases exponentially like you mention but still hapen to some extend.
But it seems like this issue is made up. In the current state the blocks are only about 20% filled with transactions and a reverting arb tx only needs 40.000 of that. BAS will further reduce it. There is no problem with blockspace.

Tx to confuse competition: Will still happen for PGA strategies. Will still happen for backrun in order to hide their best hash, but reduced.

mev equality: It wont level the playingfield. The big guys can afford more hashpower than anyone else. They can claim any atomic MEV they find and will destroy any small players. Any pre mining strategy could just be copied by them. And yes these small players exist. The chi minting bot from the other issue is an example of a small player making money. You just need to broaden your horizon.

2022-05-26 16:16 UTC, TxByTime commented
> > This might take some time, because some Validatos are still using v1.1.5.
> 
> interesting that you use such non-public information as an argument here. almost as if you are directly connected to validators and therefore judge this PR as negative because it would harm you. perhaps this PR also motivates MEV traders not to look for other validators, because then it is no longer of any use to them.

This is public information. Anyone can look it up on bscscan.

2022-05-26 17:05 UTC, ktrout1111 commented
@TxByTime 

> But you don't know the setup of the bots you don't know. There are so many small profitable bots on the chain and I doubt you, me or anyone here knows every one of it.

Fair enough. It is true that I mostly looked at the big players, and this was several months ago. I was aware of the handful of smaller successful bots, and just assumed they were running the same scheme as the big players but with fewer nodes. 

> MEV is much more than just standard Pancakeswap arbitrage. For some reason you only see that and refuse to look beyond it at the bigger Picture where the small guy's currently can make a profit. 

Yeah, I have focused on Uniswap-clone only arbitrage since that looked at the time to be the only viable game in town. I toyed with the idea of other strategies (such as non atomic) but those seemed riskier and straw-grabbier so I didn't bother. Congratulations for finding a way to profit in such a hostile environment. Sorry for calling you a liar - I was assuming you were referring to a Uniswap-only approach as I have substantial experience that such an approach with a dozen nodes cannot break even in current conditions.

By the way, it might ease your anxiety to learn that neither me, lenny, or anyone else who has posted here has the authority to merge this request. It's down to the devs, whose prior indifference on this subject suggests a low probability that this pr is accepted.

> This single entity you mention is not even picking up most of the Pancakeswap arbitrage. It has atleast two competitors and is currently not even the best on most days.

I'm not up to date, most of my analysis was done back in Feb. At the time they had one big competitor who was doing just as well as them on some days, but for some unknown reason completely shut down a few months ago. It's also come to my attention that the dominant whale in question also shut down all of their operations about 23 hours ago:

https://bscscan.com/address/0x4834c08f5aaab44c8bdeddc386eca4029e3c6c40#tokentxns
https://bscscan.com/address/0x3948392c35fabb910d6ebe222b570fb52bf0844a#tokentxns
https://bscscan.com/address/0x468fc54b82b590d1698251d2bce1a9f91c43f042#tokentxns
https://bscscan.com/address/0xaf25d6494a341675186f975c4cbc081fdac05dbc#tokentxns

I don't currently have the patience to check through their tx history to see if this might be because an even bigger fish has arrived on the scene or not.

2022-05-26 17:20 UTC, TxByTime commented
@[ktrout1111](https://github.com/ktrout1111)

>Yeah, I have focused on Uniswap-clone only arbitrage since that looked at the time to be the only viable game in town.

Uniswap only arb is the most optimized in this game. The big guys have build teams and have been optimizing their code together since Uniswap exists. You can not expect to compete with these guys after a few months of building alone. Like I said, there is no free launch and you might have to put some of your capital at risk to make money in MEV.

>It's also come to my attention that the dominant whale in question also shut down all of their operations about 23 hours ago

They did not shut down. They migrated to a new contract version. Or maybe they didn't like all the attention that you are givin them here...

2022-05-26 23:26 UTC, cwazy2020 commented
> @[ktrout1111](https://github.com/ktrout1111)
>  Or am I just a bot operator worried about his income source? 

Yes, anyone objective should believe this to be the case.  You created an account here specifically to fight this issue, and there is only one group of people that would be threatened by it enough to do that.  I can say with ~95% confidence that you are involved with at least one of three bots I have been watching for ~1 year.

> 
>  There are so many small profitable bots on the chain 

There actually aren't really that many.  I wrote a tool that does nothing but analyze these things.  Many of the largest players have spread their operations out over a large number of contracts, but can still be tied together.  In fact one of you guys with hundreds of spam nodes uses over 100 unique contracts, using the same method ID lol.  Even those of you that use fallback functions and random method IDs, it's relatively easy to tell using some disassembly.  Basically, no small guys are making anything.

Do you think that some of us don't see this?  We do, you're not fooling anyone.  Just because we don't have the financing for hundreds of nodes, doesn't mean we are stupid.  Enough with spamming 100+ same-price, same-nonce backruns.  Yep, we see that too.  You guys are killing the network.

IMO, this approach of ordering by hash should be implemented.  It isn't perfect, but it addresses many of the issues that have created such a spam filled, completely unfair landscape.  I am aware that this proposal will likely fail, because the people fighting it are making 9 figures per year.  But for what it's worth, it should be.

2022-05-27 06:39 UTC, de-ltd commented
Bots will just launch tx’s from multiple “nodes” hoping it get lucky with hashes. Solves nothing really.

2022-05-27 10:24 UTC, TxByTime commented
@[cwazy2020](https://github.com/cwazy2020)
>Yes, anyone objective should believe this to be the case. You created an account here specifically to fight this issue, and there is only one group of people that would be threatened by it enough to do that. I can say with ~95% confidence that you are involved with at least one of three bots I have been watching for ~1 year.

Why should a big player fight this issue? They have enought funding to buy alot of computing power and claim every single atomic MEV opportunity after this PR. They like this PR and will not fight it. You don't see me accusing anyone that likes it of being one of them.
I don't get how my new or empty account is an issue.  Most people in this disscussion have an empty github or relative new account.

>IMO, this approach of ordering by hash should be implemented. It isn't perfect, but it addresses many of the issues that have created such a spam filled, completely unfair landscape. I am aware that this proposal will likely fail, because the people fighting it are making 9 figures per year. But for what it's worth, it should be implemented.

>Enough with spamming 100+ same-price, same-nonce backruns with the gas allowance/input changed slightly so that you have unique hashes that clog up the network and take unique paths to validators for the cost of a single tx. Yep, we see that too. You guys are killing the network.

It doesn't solve the fake nodes: They will still be there for PGA strategies. It does not solve same nonce spam: This will still be there to confuse the competition. This PR will make the landscape even more unfair. No one will be able to compete for anything atomic anyone. This PR might reduce some tx spam that lands on the chain - but blockspace is not an issue.
It does not address the spam issue for PGA's which, if you read my previous response, is just as bad. But somehow that is not discussed or addressed here.
The total amount of MEV (including Sandwich, Liquidatons) on Eth was about one billion last year. I don't see how any team could extract the same amount of money on BSC doing Uniswap arbitrage when competing against atleast three other teams. This is a claim without any proof from you. Show us some proof they actually made that if you really have build this tool. I also doubt this tool finds every bot on this big chain.

Where is your proof that the network is dying or being killed? This seems to be made up. I don't see any recent github issues of other node operators having sync problems? There are no hotfixes on the client or scheduled maintance periods where the whole blockchain is stopped like on Polygon.
This PR does not solve the network spam created by PGA's. There are more PGA's than backruns, since a lot more startegies (CEX-DEX, Crosschain, Sandwich, advanced Strategies...) require them. I don't see this issue addressed here. Maybe because this doesn't effect you building your own arbitrage bot? This change seems to have been brought forward by people trying to build one thinking it gives them a chance to compete and failing to realize that this won't be the case.

2022-05-27 10:39 UTC, ktrout1111 commented
@cwazy2020

> Basically, there is a handful of highly successful teams, and no small guys are making anything.

Exactly this. Everyone on here complaining that changing the current sort method "would crush the little guy" seem oblivious to the fact that the little guy has already been crushed for the last year. While sorting by hash would allow the bigger players to buy more hash power, this would NOT crush the smaller players out of existence, they would just get a smaller slice. Their argument is akin to saying that no one should bother mining BTC or ETH at home with their stack of GPUs because gigantic mining farms exist in China. They still get a share, just a much smaller one. 

As things stand with sort by time, the smaller players/triers get no share at all because participation requires catastrophic fee expenditure. With sorting by hash, the only cost is short burts of electricity usage and a very occasional errantly sent tx. The little guy still gets a share of the profit this way. This is the key defining feature of this PR, and that is why the status quo feels threatened by it.

2022-05-27 10:41 UTC, ktrout1111 commented
> Enough with spamming 100+ same-price, same-nonce backruns with the gas allowance/input changed slightly so that you have unique hashes that clog up the network and take unique paths to validators for the cost of a single tx. Yep, we see that too. You guys are killing the network.

BINGO. You see it. I see it. Anyone who takes the time to analyse the network traffic sees it. The evidence is damning and irrefutable.

2022-05-27 11:10 UTC, ktrout1111 commented
@TxByTime 

> Uniswap only arb is the most optimized in this game. The big guys have build teams and have been optimizing their code together since Uniswap exists. You can not expect to compete with these guys after a few months of building alone.

Say what now? The only edge they have here is profit optimisation, which is entirely contingent on winning the race to the backrun spot. It's a bridge to be crossed when you come to it. Most of us don't even reach this bridge because of the tx sort method. It's a moot point. Besides, the predecessor whale to the current hegemon was doing very well with 2 and 3-pair arbs, which are easy to calculate expediently. The 4 and 5-pair showboating we see these days is just wringing the sponge a bit more. Besides, if these devs are so much more skilled than the rest of us, how come some of their arbs a few months ago were running at a net loss? It looked like they weren't even bothering with gas estimation. They are/were winning by brute force, not skill.

> Like I said, there is no free launch and you might have to put some of your capital at risk to make money in MEV.

A more paranoid man than I might suspect you were trying to send me off beating in the bushes to throw me off the scent. I and others here have already beaten those bushes, slashed them with machetes, and burned them to the ground only to find scorched earth underneath. You claim to be happy picking crumbs off the floor while the whales gorge on a never-ending banquet, but this PR would enable the rest of us, including you, to have a seat at that table and eat like a man instead of like a dog.

2022-05-27 11:13 UTC, ktrout1111 commented
> The total amount of MEV (including Sandwich, Liquidatons) on Eth was about one billion last year. I don't see how any team could extract the same amount of money on BSC doing Uniswap arbitrage when competing against atleast three other teams. 

I agree that 9 figures is an exaggeration. It's DEFINITELY 8 figures though. In the words of Tony Montana, "That's some serious money."

2022-05-27 11:20 UTC, cwazy2020 commented
> > The total amount of MEV (including Sandwich, Liquidatons) on Eth was about one billion last year. I don't see how any team could extract the same amount of money on BSC doing Uniswap arbitrage when competing against atleast three other teams.
> 
> I agree that 9 figures is an exaggeration. It's DEFINITELY 8 figures though. In the words of Tony Montana, "That's some serious money."

Total arb profits did exceed $100 million in the last year on BSC.  There is one entity that accounted for about 1/2 of that.  9 figures is not billions, it's hundreds of millions.  But you're right, even if it were 8 figures, that would also be a lot of money.

2022-05-27 11:38 UTC, degenDever commented
This issue was resolved long ago in the Ethereum community. Sorting by time is optimal.
1. Whichever sorting algorithm is used, first of all, it does not solve the problem that validators decide on their own preferences for the order in which transactions are packaged. Even with tx hash sorting, you can't prove that the Validator intentionally broke the transaction packaging order. The Validator can just claim that some transactions were not received by p2p or txpool was full.  And users can't prove the order was changed by validator.

2022-05-27 11:44 UTC, TxByTime commented
[ktrout1111](https://github.com/ktrout1111)
>You claim to be happy picking crumbs off the floor while the whales gorge on a never-ending banquet, but this PR would enable the rest of us, including you, to have a seat at that table and eat like a man instead of like a dog.

This PR will not allow you to get a seat on the table. How are you going to compete against someone that, according to you, has $50 million in profits to buy hash power? The whales going to gorge more after this PR and you will not have a chance to compete for any atomic strategies. These exisits, even if you seem to be unable to find them.

For any atomic MEV this PR will only help the whales. This should not be the purpose of this PR.
This PR also does not improve the Network:
It doesn't solve the fake nodes: They will still be there for PGA strategies. 
It does not solve same nonce spam: This will still be there to confuse the competition. 
This PR might reduce some tx spam that lands on the chain - but blockspace is not an issue.
This PR does not improve transparency:
A corrupt Validator can still choose to ignore any tx and claim they received them too late or include one with a worse hash. They don't even need to obey by the new sorting mechanism since there is no punishment for it.

2022-05-27 12:09 UTC, ktrout1111 commented
@degenDever

> Sorting by time is optimal.

It is very optimal for a handful of whales. Perhaps you are one of them?

> If you sort transactions by hash, the BSC network becomes more congested

I have already explained, in agonising detail, how this is NOT the case. Like many here, you make assertions with nothing to back them up.

2022-05-27 12:53 UTC, degenDever commented
> @degenDever
> 
> > Sorting by time is optimal.
> 
> It is very optimal for a handful of whales. Perhaps you are one of them?
> 
> > If you sort transactions by hash, the BSC network becomes more congested
> 
> I have already explained, in agonising detail, how this is NOT the case. Like many here, you make assertions with nothing to back them up.

I wish I was one of the whales, but I'm not.

As I have explained, your claim has been proven to be unfounded, and you can rely on other chains rather than your own fantasies. But I'm guessing you won't, because other chains don't use such stupid algorithms

2022-05-27 12:55 UTC, lennybakkalian commented
> @TxByTime: I have already explained, in agonising detail, how this is NOT the case. Like many here, you make assertions with nothing to back them up.

he repeats himself without providing any arguments. it is obvious that he does not want this PR to be merged out of self-interest.


> Why should they replace their infra? They run another bot that competes in PGA's - they won't replace their infra. They need that to win there. Since this PR won't get rid of PGA's it won't remove these "fake" nodes.
My other point also still stands: They will still use it if it means they can get a tx a few ms faster or can send it a few ms later to a validator. At some Point it will be cheapter to run these "fake" nodes as buying more hashpower.

Why would that be the case? currently the big guys are near the validator anyway. they just rent a second server on the other side of the world and then get the tx there as one of the first and then mine their hash. And as @ktrout1111 already wrote, the difficulty to find a better hash increases exponentially. tx spam would simply not exist anymore, or would be drastically reduced. Fake nodes would also not exist anymore, because you don't have to spam tx.

You would move this whole competition outside the blockchain. and that's what this pullrequest is about. not about MEV traders or sharing the MEV opportunities fairly. The blockchain is capitalism. I think we are discussing a completely different topic here.

> @de-ltd: Bots will just launch tx’s from multiple “nodes” hoping it get lucky with hashes. Solves nothing really.

Almost as if you don't even read through the PR but the main thing is to give your ignorant opinion without reading through any previous comments.

Somehow we are going around in circles here and i don't think it will come to a solution in the end where the other side will be convinced.

2022-05-27 13:01 UTC, degenDever commented
> > @TxByTime: It doesn't solve the fake nodes: They will still be there for PGA strategies.
> 
> he repeats himself without providing any arguments. it is obvious that he does not want this PR to be merged out of self-interest.


When you write code here, you say that you are doing it for fairness, for justice, and other people are talking to you about things, you don't talk about things, but you say that people are doing it for their own interests, and your behavior makes me think that you are doing it for your own interests

2022-05-27 13:06 UTC, lennybakkalian commented
> When you write code here, you say that you are doing it for fairness, for justice, and other people are talking to you about things, you don't talk about things, but you say that people are doing it for their own interests, and your behavior makes me think that you are doing it for your own interests

Of course I do this out of self-interest, like everyone in this PR. I had to rewrite my geth so that peers get kicked if they don't send tx or blocks, because otherwise I always went out of sync. And that pisses me off because I suspect they are all fake nodes. (were also no light nodes, because I have this completely turned off)

Also, for MEV opportunities, since the current situation is: if you are not connected to a validator, you cannot participate. And the focus to participate in MEV should not be to be connected to as many validators as possible, or do you see it differently?

2022-05-27 13:18 UTC, degenDever commented
> > When you write code here, you say that you are doing it for fairness, for justice, and other people are talking to you about things, you don't talk about things, but you say that people are doing it for their own interests, and your behavior makes me think that you are doing it for your own interests
> 
> Of course I do this out of self-interest, like everyone in this PR. I had to rewrite my geth so that peers get kicked if they don't send tx or blocks, because otherwise I always went out of sync. And that pisses me off because I suspect they are all fake nodes. (were also no light nodes, because I have this completely turned off)
> 
> Also, for MEV opportunities, since the current situation is: if you are not connected to a validator, you cannot participate. And the focus to participate in MEV should not be to be connected to as many validators as possible, or do you see it differently?
> 
> Let's assume that things stay the same as they are now: New MEV participants would try to find the validators. When this happens, it will be a fight to see who gets a free peer slot. Since maybe not all validators use sentries, this would pose a bigger problem, as these validators would be left naked and spammed by connection requests to get a free slot as soon as one becomes available.

Assuming that the transactions are sorted by hash, since size of `txpool` is limited, mev arbitrageurs will send a lot of transaction attempts to fill the pool as quickly as possible, so that there is no room for other arbitrageurs, which will give you more 'fake Nodes'. Because their goal changed from `being the fastest to get to the txpool` to `being the fastest to fill the txpool`

2022-05-27 13:19 UTC, TxByTime commented
[ktrout1111](https://github.com/ktrout1111)

I think you should stop accusing anyone that disagress with you of being a whale. I think I have made my point clear that this PR threatens every small bot operator and only helps these whales. Why should the whales argue against it? They can afford to buy the hash power. Maybe its time to turn the table: Maybe you are the whale here since you are pushing this PR so hard?

>>    If you sort transactions by hash, the BSC network becomes more congested

>I have already explained, in agonising detail, how this is NOT the case. Like many here, you make assertions with nothing to back them up.

I think their point was that the network will be congested during the launch of a new token. A large amount of users buying will cause this. The Liquidity sniper might still spam a few blocks in order to be the first if it gives them an advantage. This PR won't make this better or worse.

[lennybakkalian](https://github.com/lennybakkalian)
I'm providing arguments but you seem to be missing the point. Maybe I don't do a good job explaining it or you just won't understand it. Let be try again:
> > Why should they replace their infra? They run another bot that competes in PGA's - they won't replace their infra. They need that to win there. Since this PR won't get rid of PGA's it won't remove these "fake" nodes.
    My other point also still stands: They will still use it if it means they can get a tx a few ms faster or can send it a few ms later to a validator. At some Point it will be cheapter to run these "fake" nodes as buying more hashpower.

> Why would that be the case? Currently the big guys are near the validator anyway. They just rent a second server on the other side of the world and then get the tx there as one of the first and then mine their hash. And as @ktrout1111 already wrote, the difficulty to find a better hash increases exponentially. Tx spam would simply not exist anymore, or would be drastically reduced. Fake nodes would also not exist anymore, because you don't have to spam tx.

This point was about fake nodes. Your argument is that this PR gets rid of them. But I'm telling you that the same guys that do backrun arbitrage also have strategies that require to do PGA. For those PGA strategies they still need those nodes: PGA is about reacting fast to the gasPrice increase of the competition. They will still need fake nodes to gain those few extra ms advantage. Do you get it now why this PR won't get rid of them? See bellow for a potential solution.

>Also, for MEV opportunities, since the current situation is: if you are not connected to a validator, you cannot participate. And the focus to participate in MEV should not be to be connected to as many validators as possible, or do you see it differently?

I have already said MEV is not only backrun uniswap arbitrage. You can compete for some backrun MEV opportunities without peering with the validators.

>Of course I do this out of self-interest, like everyone in this PR. I had to rewrite my geth so that peers get kicked if they don't send tx or blocks, because otherwise I always went out of sync. And that pisses me off because I suspect they are all fake nodes. (were also no light nodes, because I have this completely turned off)

See above why this PR won't get rid of the fake nodes. I don't have any issues staying sync on any of my nodes - even during high congestion. 
Maybe you can do a PR with these geth changes? This might get rid of the fake nodes for everyone including the validators? In my opinion that would be the best solution for the fake node problem.

2022-05-27 13:20 UTC, ktrout1111 commented
@TxByTime 

> This PR will not allow you to get a seat on the table. How are you going to compete against someone that, according to you, has $50 million in profits to buy hash power? 

Aha! A quantitative argument. Let's crunch the numbers on this. Let's assume that the current total combined profit is $100m, 50% of which goes to Mr Whale. Let's say they are willing to sink a whopping 80% of their profits into hash power. You claim that with their hugely deep pockets that they will easily surpass their existing share of the pie. Let's see what the numbers say..

With an annual budget of $40 million they head over to AWS and take a look at what they can get. As everyone here knows, standard EC2 cores are utter garbage, about 3-5x slower than a real physical CPU core, so that's not an option. They need to shell out for dedicated servers.

https://aws.amazon.com/ec2/dedicated-hosts/pricing/

Looking at the bulk compute-optimised options, it's a choice between c6a AMD EPYC or the cheaper AWS Graviton. It's very hard to see from benchmarks (https://www.phoronix.com/scan.php?page=article&item=graviton3-amd-intel&num=2) which would be better for tx mining. For the sake of this example, I will take one AMD EPYC core on a c6a instance to be roughly equivalent to 1 physical AMD Zen 3 Core in a home computer. 

Paying a year up front gets Mr Whale a discount - a 96 core c6a instance costs him $3,901.12 a month, or $46,913.44 a year. His budget of $40 million means he can afford 854 of these instances, for a total of 81,984 dedicated cores. Now, to assess how Mr Littlefish would fare in this environment, we need to know the total number of cores affordable by all whales combined. We said Mr Whale accounted for half of this, so let's double the above figure and say that the total number of cores owned by everyone combined is about 160,000.

Mr Littlefish's AMD Zen3 machine has 16 cores, which would account for 0.01% of the hashrate, and therefore roughly 0.01% of the profit (1 CPU = 1 vote), which comes out as about $100,000 a year. It'd call that a seat at the table. But the good news gets even better for Mr Littlefish, and worse for Mr Whale - PoW hashing is always an arms race - miners are always acquiring more and more hash rate to keep up with one another, but uh oh - Mr Whale is already tapped out! If Mr Littlefish lays out another few thousand $ for another Zen 3 to run in his basement, he stands to double his profits to $200k a year! But Mr Whale would crush himself if he doubled his hashrate - he's already sinking nearly all his profits into what he currently has.

So what we see, when we actually use math and facts instead of assumptions, is that sorting by hash would LEVEL the playing field.

2022-05-27 13:27 UTC, TxByTime commented
[ktrout1111](https://github.com/ktrout1111)

Why are you using AWS instances for this comparison? AWS is expensive. I don't think the whales will be using that to mine hashes. It will be similar to Eth mining - which obviously doesn't happen on AWS.

2022-05-27 13:31 UTC, ktrout1111 commented
>  I think I have made my point clear that this PR threatens every small bot operator and only helps these whales.

I've debunked your "points" over and over, as well as explain that the current situation is only favourable to whales and not small operators. You ask us for proof, while providing none of your own. You claim to make non atomic profits under the current climate? Prove it. Show us the contract address.

> Why should the whales argue against it?

Because the current status quo is VERY favourable for them, and this PR would change that. WHY would any of the current whales be in favour of a change to the current system? It's working absolutely beautifully for them.

> Why are you using AWS instances for this comparison? AWS is expensive.

OK, counter my argument with a cheaper provider. So Littlefish only makes $50k a year, or 30. He uses that money to buy 5 more rigs. The arms race would benefit the smaller players, I have proved that with actual math and logic.

2022-05-27 13:33 UTC, ktrout1111 commented
> If you only win 0.01% of opportunities against these whales that means you win one in 10.000tx. Each of these failed will cost you about $0.05. So your one success has to net you $500 in order to break even. There are not that many big opportunities. So while you might win 0.01% you will operate at a loss.

Utterly, utterly wrong. That's if you spam a tx, which will be very rare. "Losing" an arb in the vast majority of cases will NOT INVOLVE sending a tx, that's the WHOLE point of this. See my many posts explaining this, including the underlying math.

2022-05-27 13:44 UTC, TxByTime commented
> > If you only win 0.01% of opportunities against these whales that means you win one in 10.000tx. Each of these failed will cost you about $0.05. So your one success has to net you $500 in order to break even. There are not that many big opportunities. So while you might win 0.01% you will operate at a loss.
> 
> Utterly, utterly wrong. That's if you spam a tx, which will be very rare. "Losing" an arb in the vast majority of cases will NOT INVOLVE sending a tx, that's the WHOLE point of this. See my many posts explaining this, including the underlying math.

This is not wrong at all. You just don't seem to understand how this game will evolve:
They will wait to send their tx a few ms before the validators starts building the block. 
You will never know their best hash. Their fake nodes and good peering with the validators helps them with this. No one will be able to compete with this.

I'd like to ask you to provide counter arguments to my latest summary bellow. Some one finding this discussion might only read part of it. They might see you admiting not knowing about PGA, me providing an argument why the fake nodes will still be there because of PGA and you not delivering any counter argument except that you have "debunked" it over and over. So far you have not said anything about this argument let alone debunked it.

This PR also does not improve the Network:
It doesn't solve the fake nodes: They will still be there for PGA strategies. They will still be there in order for them to send their tx at the latest possible moment in order to hide it.
It does not solve same nonce spam: This will still be there to confuse the competition.
This PR might reduce some tx spam that lands on the chain - but blockspace is not an issue.
This PR does not improve transparency:
A corrupt Validator can still choose to ignore any tx and claim they received them too late or include one with a worse hash. They don't even need to obey by the new sorting mechanism since there is no punishment for it.
It does not level the playing field: You can't compete with the hash power of the big players. The big players will hide their best hash. So you will never know if you can submit it or not.

2022-05-27 13:53 UTC, lennybakkalian commented
> They will wait to send their tx a few ms before the validators starts building the block.
...
They will still be there for PGA strategies. They will still be there in order for them to send their tx at the latest possible moment

i doubt they will wait until the last "ms". The risk would be too great that the tx would not go through. Besides, they buy a lot of hashpower as you wrote in the previous comments. Why should they wait when they always have the best hash anyway?

lets check off all decided arguments:
PR prevents tx spam: ✅

2022-05-27 13:57 UTC, TxByTime commented
> > They will wait to send their tx a few ms before the validators starts building the block.
> > ...
> > They will still be there for PGA strategies. They will still be there in order for them to send their tx at the latest possible moment
> 
> i doubt they will wait until the last "ms". The risk would be too great that the tx would not go through. Besides, they buy a lot of hashpower as you wrote in the previous comments. Why should they wait when they always have the best hash anyway?
> 
> lets check off all decided arguments: PR prevents tx spam: ✅

Ok then they wait until the last 20ms. They start building a new one each time they receive a new one. Should be pretty easy for them to figure out when they start. Do seriously think that during 20ms their tx will reach you, you see the tx, know that they compete with you, realize your hash is better, submit your tx and get it to the validator you don't peer with? I don't think so.

2022-05-27 14:14 UTC, lennybakkalian commented
This latency problem is smaller than the hashpower problem. as said: the hash difficulty increases exponentially and to have (fast) fake nodes AND hashpower is expensive. Currently, full txs are immediately forwarded to peers/sqrt. So the tx spreads exponentially fast.

And even if in this PR it comes out that fake nodes are not eliminated from the world, at least it would prevent tx spam, as you admitted.

2022-05-27 14:19 UTC, TxByTime commented
> This latency problem is smaller than the hashpower problem. as said: the hash difficulty increases exponentially and to have (fast) fake nodes AND hashpower is expensive. Currently, full txs are immediately forwarded to peers/sqrt. So the tx spreads exponentially fast.
> 
> And even if in this PR it comes out that fake nodes are not eliminated from the world, at least it would prevent tx spam, as you admitted.

If there are three or for teams competing for a piece of a $100 million pie its not expensive.
I admit that it will prevent some backrun spam. But you have still not provided any evidence that backrun spam is a real problem for the blockchain or that there is a blockspace issue. There is no blackspace issue.

2022-05-27 14:22 UTC, ktrout1111 commented
> I'd like to ask you to provide counter arguments to my latest summary bellow. 

I have already responded to half of the points in your "outstanding" list. I haven't done the rest yet because this debate is proving to be a full time job and I have duties outside of GitHub. So far I've only addressed the points you raised that I feel qualified to address.

> It doesn't solve the fake nodes: They will still be there for PGA strategies. They will still be there in order for them to send their tx at the latest possible moment in order to hide it.

Why do either of these strategies require hundreds of fake nodes? If latency minimisation is the goal, that only requires a handful of nodes - one in each of the hotspots.

> It does not solve same nonce spam: This will still be there to confuse the competition

I already tore this one apart in a previous post.

>  and for PGA.

Maybe it wouldn't solve spam for this, but so what? This PR doesn't claim to fix all the problems of BSC, only some major ones: principally network and block spam, and MEV inequity.

> This PR might reduce some tx spam that lands on the chain - but blockspace is not an issue.

Tell that to the honest full node operators having to pay for nvme cloud storage, and lots of it, to store and transmit all the spam txs.

> This PR does not improve transparency:
A corrupt Validator can still choose to ignore any tx and claim they received them too late or include one with a worse hash. 

I've answered this one before, too. The PR wouldn't result in complete transparency, but it would improve it. It would be easy for a bot operator to determine for themselves which, if any, validators are playing dirty and avoid them. Seeing their txs always delayed by a whole block is a much more obvious signal than them being artifically delayed by a few tens of ms. 

>  They don't even need to obey by the new sorting mechanism since there is no punishment for it

This will always be true of any update that makes any modifications for any reason. Not sure what your point is.

> It does not level the playing field: You can't compete with the hash power of the big players. The big players will hide their best hash. So you will never know if you can submit it or not.

Ah, this is a very interesting point. Assuming the big players can conceal their best txs adequately, this does indeed sound like a problem. It did take me several seconds to think of a workaround, thanks to our good friend, math. Will follow up later on this when I find a spare moment.

2022-05-27 14:26 UTC, TxByTime commented
> > I admit that it will prevent some backrun spam. But you have still not provided any evidence that backrun spam is a real problem for the blockchain or that there is a blockspace issue. There is no blackspace issue.
> 
> If this PR does not eliminate fake nodes (which i think it does), then it is still an improvement if there are fewer unnecessary txs, right?

Please read my latest replies why it won't do that
TLDR: Fake nodes will still be there for PGA strategies. The will also still be there for backrun strategies so that they can decide at the latest possible time if they want to send their best hash or not and to hide their best hash.
Why don't you want to merge your geth changes? This would actually get rid of them.

2022-05-27 14:29 UTC, ktrout1111 commented
> Do seriously think that during 20ms their tx will reach you, you see the tx, know that they compete with you, realize your hash is better, submit your tx and get it to the validator you don't peer with?

What if you do peer with the validator (or its sentinel)? Some of the validators (or their sentinels) stick out like a sore thumb and are very easily hunted down and peered with. 20ms would be more than enough time to detect and react to such an event (since you, the other bot and the validator are all within 2ms of each other), even if you weren't in the lucky square root group.

2022-05-27 15:04 UTC, lennybakkalian commented
> Why don't you want to merge your peer filtering geth changes? This would actually get rid of them and help the chain.

i had also mentioned somewhere in this PR: if this becomes an official change, fake node operators can easily bypass this:

_And how would that turn out? node is kicked after x minutes if it does not send any pending transactions? Okey, then the fake nodes forward 1 tx every second and the node has already survived this check. We should not try to detect and eliminate fake nodes, but destroy the incentive to run fake nodes, otherwise it ends in a cat and mouse game._


And i don't understand this discussion anymore, we decided unanimously (with the agreement of @TxByTime) that this PR prevents spam tx.
And to me it looks like 2/3 of the active participants here think that it also eleminates fake nodes. So this PR would have no negative impact on the bsc network, except in (worst) case fix the spam tx problem.

So slowly a maintainer should stop by and give his opinion on whether there could still be unresolved problems.

2022-05-27 15:09 UTC, lennybakkalian commented
> Why don't you respond to my queston? Why don't you want to merge your peer filtering geth changes? This would actually get rid of them and help the chain.

please read my comment again. in the first sentence i answer your question

2022-05-27 15:32 UTC, lennybakkalian commented
> But this PR won't get rid of the fake nodes. They will still be there for PGA strategies, where latency is just as important as backruns.

and as i have already written, this PR would still prevent fake txs. therefore, it is an improvement, as there are no negative points.

2022-05-27 15:59 UTC, TxByTime commented
>and as i have already written, this PR would still prevent fake txs. therefore, it is an improvement, as there are no negative points.

This does not get rid of fake tx. They will still be there for PGA strategies. 
They also will send them to show competitiors their worse hashes. This will bait you into submitting a tx when they already have a better hash at the validator. This is a PvP game. They want to hurt their competition.

2022-05-27 16:14 UTC, lennybakkalian commented
> They will wait to send their tx a few ms before the validators starts building the block.

you keep contradicting yourself, inventing strategies that don't make sense just to prevent progress for this PR. 

On the one hand you write that the big guys have enough hash power to defeat everyone, on the other hand you write that they "wait" with the best hash to confuse the competition? I don't understand this logic.

I think this PR is a good try to prevent the spam tx and since you still haven't brought a reason why hash based sorting is worse than arrivaltime sorting. why don't we try it then? Why are you resisting a PR that doesn't hurt the network? or would this cause your mev revenue to drop?

2022-05-27 16:16 UTC, ktrout1111 commented
> Why do backrun strategies require hundrets of fake nodes? Your argument also aplies there: It is also just latency minimisation.

OK fine, so this PR may well not do anything to mitigate PGA spam, so what? What proportion of current network traffic is PGA spam compared to legit txs or MEV spam? Have you performed an analysis? It's funny how you claim to be so familiar with this dynamic yet not so long ago accused the rest of us of witchcraft for knowing the details of the backrun spam. Both flow through the same channels.

> This is not a healthy disscussion. Everyone in here has other responsibilities and won't dig up some old response just to follow this conversation. Just copy and paste it - i might have missed it and don't know what you are refering to.

What's not healthy discussion is accusing others of not covering points that they have already covered and being too lazy to read back over them, and then on top of that asking them to spoonfeed you that information. Likewise, I have other responsibilities than to repeat points that I have already made at least twice.

> It will still happen to mess with their competition our newcommers. They already do this and will continue to do so, even if it only gives them a tiny advantage. Where is your counter argument?

I already debunked this! Can you not read? If I repeat it a third time, you will just ignore it again and accuse me of not answering.

> It will still happen to hide their best hash. 

Right, let's get to this. Doubts have been expressed about whether this is feasible, but let's say that a whale can reliably slip their winning tx directly to the validator right before they recommit and before anyone else can respond. This would indeed change the game, but it does not take a lot of thinking (if you are honest) to see that this is not a big problem. Assuming all submitted txs are concealed, then it effectively turns the game into a blind auction. The decision by any player, big or small, whether or not to expend a tx is now based on probability rather than a global known best hash.

It will be very easy for all bot operators to calculate the approximate global combined hash rate at any given time based on recent block data. From this, they can calculate the _probability_ that their current best local hash is indeed the best global hash. They can then decide their own threshold probability that warrants spending $0.05 on a tx. So yes, this _would_ involve some fee drawdown, but that can be tuned according to the bot operator's personal risk preference.

Had you considered this? It's pretty obvious. It's almost as if you want these things not to be true...

> This does not get rid of fake tx. They will still be there for PGA strategies.

This PGA thing seems to be the only leg you have left to stand on, and it's a weak one at that..

2022-05-27 16:20 UTC, ktrout1111 commented
@lennybakkalian 

> On the one hand you write that the big guys have enough hash power to defeat everyone, on the other hand you write that they "wait" with the best hash to confuse the competition? 

I think what he means is they keep hashing while "waiting", and send whatever their best hash is to the validator at the last moment.

2022-05-27 16:22 UTC, ktrout1111 commented
> Only way to get rid of PGA's is a fixed gasPrice.

Which will never happen. Does that mean we can put this whole PGA thing to bed as a problem that cannot be solved by this PR, or any other?

2022-05-27 16:35 UTC, ktrout1111 commented
> They also will send them to show competitiors their worse hashes. This will bait you into submitting a tx when they already have a better hash at the validator. 

I'm going to say this one last time, as I've been over this multiple times. Only a fool would fall for these fake hashes. The solution: run a full node, only act on full bodied, validated txs. End of discussion. You repeat this point over and over again long after it has been dismissed.

Only savvy bot operators survive under any system or tx ordering method. For instance, fake mark txs could trick a foolish bot into chasing arbs that don't exist. Even without malicious actors, it already takes a great deal of care and filtering to avoid "mirage" arbs, due to some of the pitfalls that come with irregular pair and token contracts. You know this. I know this. Everyone reading this thread knows this. It's minimum required knowledge to run a bot. No one who has navigated these hurdles is going to fall for this cheap trick that you cling to as a reason not to merge this PR.

2022-05-27 17:15 UTC, TxByTime commented
[lennybakkalian](https://github.com/lennybakkalian)
>On the one hand you write that the big guys have enough hash power to defeat everyone, on the other hand you write that they "wait" with the best hash to confuse the competition? I don't understand this logic.

I don't see any contradicting things here: There will be two or three teams with similar hashpower. They will wait until the last possible moment to submit their tx to be certain they have the best hash and to hide their best hash from every other player. How is that contradicting? This is the natural evolution of this game should that PR be merged.

@ktrout1111 
>OK fine, so this PR may well not do anything to mitigate PGA spam, so what? What proportion of current network traffic is PGA spam compared to legit txs or MEV spam? Have you performed an analysis? It's funny how you claim to be so familiar with this dynamic yet not so long ago accused the rest of us of witchcraft for knowing the details of the backrun spam. Both flow through the same channels.

Look at some blocks. The first few txs will be from bots that did PGA. Most of the time only the first is non reverting. They are in every block. You claim to have done network analysis. You should have noticed the PGA spam when doing that.

>>They also will send them to show competitiors their worse hashes. This will bait you into submitting a tx when they already have a better hash at the validator.

>I'm going to say this one last time, as I've been over this multiple times. Only a fool would fall for these fake hashes. The solution: run a full node, only act on full bodied, validated txs. End of discussion. You repeat this point over and over again long after it has been dismissed.

I am never talking about only sending hashes. You can never act on these alone.
You don't get my point. Maybe my choice is words is a little confusing so I try again: 
This is about nonce spam. They send their best full transaction with the best hash to the validator and only to the validator. Next they send a full transaction with a worse hash and same nonce to everyone else. This will bait you or their competition into submitting a tx when they already have a better hash at the validator.
The real transaction won't be propagated to anyone until the block is already under construction.
This is similar to what they are doing now, has been observed by you and does not improve the current state.

Since this discussion clearly seems to be leading nowhere and both of you refuse to accept the negative sides of this PR I am going to stop participating and leaking all of my knowledge. This discussion is already a tutorial on how to manipulate the p2p layer on any geth fork for any newcomer or small bot operator that wasn't aware of that.
The Validators and developers should just make the decision based on the arguments provided here and in the old Eth discussion.
Maybe they can ask the Eth team for advice on this matter. The Eth team has more expierence than all of us together and provide them with some additional inside and dangers we might have missed. The external neutral viewpoint of them might also help to resolve this.
My last bit of advide for both of you: If you can not make any money under the current system, you won't under the new. The big players have already seen this PR on twitter and discord and are already atleast five steps ahead of you. They probably already found ways to exploit the hash system that have not been disscussed here. You won't be able to compete against five teams working 18 hours, seven days weeks after this PR. It is not going to level the playing field of uniswap arbitrage and going to kill any other atomic MEV strategies.

2022-05-27 17:25 UTC, ktrout1111 commented
> You don't get my point. Maybe my choice is words is a little confusing so I try again:

I deleted that post as soon I realised I had misread "worst" as "best". Apologies for the confusion.

2022-05-27 17:44 UTC, ktrout1111 commented
> I have more expierence in this game than both of you together:

How can you possibly know how much experience either of us has? Of all the baseless, unquantified claims you have made so far, this has got to be the boldest.

2022-05-27 17:45 UTC, TxByTime commented
> > I have more expierence in this game than both of you together:
> 
> How can you possibly know how much experience either of us has? Of all the baseless, unquantified claims you have made so far, this has got to be the boldest.

You have both told me how much time you have spend doing this?

2022-05-27 17:45 UTC, xasdasd1 commented
@TxByTime I think you are absolutely right about this stuff. Is there any way we can have a chat in private, to discuss more about this? I'm a small player, unable to compete with the top ones, but I still have some success and insights.

2022-05-27 17:47 UTC, xasdasd1 commented
@ktrout1111 I think the current system is fair enough. Whoever is the fastest & more creative, gets to the top. You really think there are persons who have striken a deal with every validator that's out there, at the same time? Top players, get first no matter the validator.

2022-05-27 17:52 UTC, 0xEcE commented
Why is being able to compete with certain entities a necessity to merge that PR? This PR clearly helps the overall health of the network, being able to compete with whales or helping people that are desperate to make money in the current system shouldn't be the primary focus as is discussed all the time.

2022-05-27 18:09 UTC, xasdasd1 commented
> 

I don't think this will improve the network spam. @TxByTime has already made strong arguments, which I'm not going to repeat.

Not sure why you think fairness should not be the primary focus. Trading activities will always be an important part of this, and we want everyone to have an equal chance, right?

2022-05-27 18:26 UTC, TxByTime commented
@ktrout1111 

Sorry I just have to make another post. I found a mistake in your calculation that I just have to point out:
$100,000,000 total profit * 0.01% = $10,000 and not $100,000. That is a massive difference.
You can not even affort to rent a single AWS Server with this income.

@xasdasd1
I have a discord with the same name. You can find me on the BNB chain server.

2022-05-27 18:45 UTC, lennybakkalian commented
> Whoever is the fastest & more creative, gets to the top.

at the expense of the network or the full node operators?

> I don't think this will improve the network spam

a new freshly created account that is against the PR. no longer surprises me here...
maybe you can save yourself such comments? they don't help. i can also say: @ktrout1111 makes good arguments, so he is right.

maybe you should respond to the counter-arguments that are brought up all the time.

2022-05-27 18:50 UTC, 0xEcE commented
> @0xEcE I don't think this will improve the network spam. @TxByTime has already made strong arguments, which I'm not going to repeat.


No he hasn't, he just repeated what the ETH team came up with under different circumstances and all his alleged counterclaims were debunked. 

> Not sure why you think fairness should not be the primary focus. Trading activities will always be an important part of this, and we want everyone to have an equal chance, right?

What is fair? In order for people to make money, others have to lose money, that's how trading and inherently the blockchain as a business model works. If you think that you have a chance to compete with the top players in the current meta you are far from reality. The only opportunities "new players" or "small fishes" can catch will always be the ones the top players don't care about. You can always have the lowest latency across the globe with certain infrastructure but you can't have 100% computing power.
As pointed out you will have a relative portion of the computing power available and with that a certain percentage cut of all opportunities. So on top of "your alpha" you have the chance to make more money by getting parts of ALL available opportunities.
Another thing to keep in mind is that the current change will require everyone to develop new technology (fresh start) giving everyone that just started a fair starting point. Right now the top players are way too established and work in teams, leaving the new or smaller guys forever behind.

2022-05-28 00:55 UTC, xasdasd1 commented
> > Whoever is the fastest & more creative, gets to the top.
> 
> at the expense of the network or the full node operators? (enough discussed in previous comments)
> 
> > @TxByTime I think you are absolutely right about this stuff.
> 
> > I don't think this will improve the network spam. @TxByTime has already made strong arguments, which I'm not going to repeat.
> 
> a new freshly created account that is against the PR. no longer surprises me here... maybe you can save yourself such comments? they don't help. i can also say: @ktrout1111 makes good arguments, so he is right.
> 
> maybe you should respond to the counter-arguments that are brought up all the time.
> 
> in this PR, the following things were discussed and they are now fact for me:
> 
> * This PR does not worsen the bsc network in any way.
> * This PR (could) lead to the fake nodes or tx spam to stop. (which i think will happen)

Don't see the problem with me making an account just to post here. Already, most accounts you see here are new accounts, not just mine. Some people prefer anonimity, no need for everyone to post pictures of themselves. My real github account contains work & personal info, which I just don't want to share. Anyway, let's stick to the topic, not conspiracy theories.

Your real motive is to have a chance at arbitraging and make some profits for yourselves, this is quite obvious by now based on the discussion. You argue that this is going to benefit everyone. This PR does exactly the opposite, you are going to close the door for the little guys.

Whales already have the resources find the best hash. They can never be sure which one is the best, so they will still spam txes. Same goes for the little guys, they will also spam txes. Sometimes they might be lucky, so they will be happy with spamming. This might actually increase the spamming of little guys, who are the majority. It can actually worsen the network.

With the fake nodes problem I agree, but absolutely no need to change tx sorting for that. It has to be treated directly, not as a side effect of tx sorting. I'm not a geth expert, but a better protocol for verification of the peer state would be the right way to fix this.

2022-05-28 02:26 UTC, xasdasd1 commented
> > Whoever is the fastest & more creative, gets to the top.
> 
> at the expense of the network or the full node operators? (enough discussed in previous comments)
> 
> > @TxByTime I think you are absolutely right about this stuff.
> 
> > I don't think this will improve the network spam. @TxByTime has already made strong arguments, which I'm not going to repeat.
> 
> a new freshly created account that is against the PR. no longer surprises me here... maybe you can save yourself such comments? they don't help. i can also say: @ktrout1111 makes good arguments, so he is right.
> 
> maybe you should respond to the counter-arguments that are brought up all the time.
> 
> in this PR, the following things were discussed and they are now fact for me:
> 
> * This PR does not worsen the bsc network in any way.
> * This PR (could) lead to the fake nodes or tx spam to stop. (which i think will happen)

Don't see the problem with me making an account just to post here. Already, most accounts you see here are new accounts, not just mine. Some people prefer anonimity, no need for everyone to post pictures of themselves. I simply don't want to share my real account and personal info, as most of users. Anyway, let's stick to the topic, not conspiracy theories.

With the fake nodes problem I agree, but absolutely no need to change tx sorting for that. It has to be treated directly, not as a side effect of tx sorting. I'm not a geth expert, but a better protocol for verification of the peer state would be the right way to fix this.

1. "It does not worsen the network" - not proven, so not a fact.
2. You say this PR "could" fix issues. Since you're using the term could, then this is also not a fact, but a possibility.

"fact" is a pretty strong word for what we have here.

2022-05-28 06:45 UTC, ModifiedGeth commented
My two cents:

**Background**
I am one of 'them' that made 7 figures in the last 14 months. Currently over 30 modified nodes running in different countries. My main profits are from arbitrage between the known exchanges. With limited programming background I started botting in early 2021 and after few weeks it became my full time job. Till date I am still making a lot of profit, even with the amount of competitors.

**Opinion**
I respect the effort made in this pull and I support this change as it will create a healthier network. Yes it will have impact on my nodes/profit, but this change will create more opportunities and eliminate other bots.

2022-05-28 07:25 UTC, de-ltd commented
When people with 100+ machines connected to the network fire off hundreds of transactions to play low hash bingo how is that going to help the network? 


I’m sorry but a lot of people on here really don’t have a clue and I really hope the people in charge of implementing this stuff have more of an idea. 

Sent from my iPhone

> On 27 May 2022, at 16:27, TxByTime ***@***.***> wrote:
> 
> ﻿
> ktrout1111
> 
> Why are you using AWS instances for this comparison? AWS is expensive. I don't think the whales will be using that to mine hashes. It will be similar to Eth mining - which obviously doesn't happen on AWS.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-05-28 11:36 UTC, lennybakkalian commented
@xasdasd1
> Don't see the problem with me making an account just to post here. 

my problem with newly created accounts is that you don't know if they are unique people. new people keep coming in here who don't bring any new arguments and we've been going around in circles for days now.

> I'm not a geth expert, but a better protocol for verification of the peer state would be the right way to fix this.

this will not work. you will never detect fake nodes. you will always find a way around it. you could also run a single full node and connect the fake p2p nodes to it to query the state and thus survive this check.

> "It does not worsen the network" - not proven, so not a fact.

i wrote this because so far no one has made a counterargument against this PR why it would do the network any harm

> You say this PR "could" fix issues. Since you're using the term could, then this is also not a fact, but a possibility.

if you read through the previous comments of mine, you will notice that i strongly believe that this PR will prevent the fake nodes / spam tx. But since people keep saying here that this PR is useless and we have not agreed, I used the word "could".

We are constantly discussing whether this PR is useful or not. But as long as it doesn't harm the network and half of us are convinced that it eliminates fake nodes and fake txs, we can give it a try. that's my point.

> "fact" is a pretty strong word for what we have here.

oh and when are you allowed to speak facts? if you allow it? This PR has now been open for 11 days and is the subject of heated discussion. If in the discussion it comes out that tx spam is prevented, it is a fact for me. what is wrong with that? you are welcome to bring counter-arguments (which have not yet been mentioned).


@de-ltd 
> When people with 100+ machines connected to the network fire off hundreds of transactions to play low hash bingo how is that going to help the network?

what the hell is low hash bingo? if by "hash bingo" you mean that by luck you have a better hash than someone who scores mining farms you are completely wrong? And that's exactly what this PR is supposed to prevent, because then it wouldn't be worth it to send out quickly generated hashes because there is always a party that has a lot of hash power and will beat you anyway.

2022-05-28 14:06 UTC, xasdasd1 commented
> oh and when are you allowed to speak facts? if you allow it? This PR has now been open for 11 days and is the subject of heated discussion. If in the discussion it comes out that tx spam is prevented, it is a fact for me. what is wrong with that? you are welcome to bring counter-arguments (which have not yet been mentioned).

I didn't say I have to allow it. I was just saying it's not a real fact. I just find it disingenuous to name these things facts, while they are just opinions. You have your arguments, others have theirs.

In my view, it's not going to stop spamming txes, people will still compete with their best hashes and will spam. Saying that people will just stop because they have no chance is complete nonsense. You just said everyone has a chance. They are spamming right now, in the current state, where you say there are just a handful of whales getting the whole pie. @de-ltd made a fair point, people will have hundreds of machines crunching new hashes, and sending their best ones, he didn't say "fake nodes". As @ktrout1111 mentioned in a reply, people can calculate their probability of their local hash being the best one globally, and will act on these opportunities. Now just imagine everyone is doing that, obviously mempool is going to be spammed. This will be a blind auction, and unnecessary randomness is being introduced, which can actually damage the network. However, I don't claim this as a "fact", and also not proclaiming myself an expert.

To me it seems you are pushing this out of self-interest, while parading as a justice warrior for the network and everyone. Don't want to make this personal, but it's hard when you act disingenuously and put words into peoples mouths. So let's stop with this kind of things, accusing people of having new accounts, of being whales with hidden self-interests just because they don't agree with your PR.

2022-05-28 14:12 UTC, xasdasd1 commented
> de-ltd

> When people with 100+ machines connected to the network fire off hundreds of transactions to play low hash bingo how is that going to help the network? I’m sorry but a lot of people on here really don’t have a clue and I really hope the people in charge of implementing this stuff have more of an idea.

I also hope this hash lottery mechanism is not going through. The opposing side, at one point argues that everyone will have a part of the pie. Then when you bring out your spamming concern, they suddenly switch to "only a few have mining farms, so there's no reason for people to compete"

2022-05-28 14:33 UTC, lennybakkalian commented
> @de-ltd made a fair point, people will have hundreds of machines crunching new hashes, and sending their best ones, he didn't say "fake nodes".

so you agree that this PR will lead to fewer fake nodes? or am I twisting the words in your mouth with this, too?
currently there are fake nodes AND spam txs. This PR would fix both in my eyes.

i would like to reference @ktrout1111's [comment](https://github.com/bnb-chain/bsc/pull/915#issuecomment-1138580348) where it describes why hash based tx sorting would prevent tx spam. please read all previous comments

> I also hope this hash lottery mechanism is not going through.

currently arb txs are spammed right after they are received. with this PR, txs would not be created until a better hash is found. i'm tired of having to explain this for the umpteenth time. "hash lottery mechanism" is a complete misnomer. the big guys with lots of hash power don't need luck. Let me explain it with an example so that even you can understand:

Suppose a lottery is started. The probability that you win is 1 in 10k.
The big people have a hashpower of 5k. It would not make sense for the small arb traders to send out 1 ticket for each arb trade, because the probability of winning is far too small and would never be profitable. 

honestly i have no idea what we are discussing anymore. sharing mev opportunities fairly would be a nice side effect but is not an argument for any side. first fake txs or fake nodes should be eliminated from the world. and if this PR improves one thing, it should be merged.


> To me it seems you are pushing this out of self-interest

somehow i find it cheeky when you join a discussion and don't even read through all the comments. i have set my point of view clearly and don't feel like explaining it again.

> people can calculate their probability of their local hash being the best one globally, and will act on these opportunities. Now just imagine everyone is doing that, obviously mempool is going to be spammed.

sorry but this makes no sense to me. what should the mempool be spammed full with? random txs? better hashes?

2022-05-28 15:45 UTC, xasdasd1 commented
> so you agree that this PR will lead to fewer fake nodes? or am I twisting the words in your mouth with this, too?
> currently there are fake nodes AND spam txs. This PR would fix both in my eyes.

I clearly said in a previous reply that I agree with the fake node problem. But again, you're cherry picking parts of responses, just as you do with everyone who shares a different opinion in this PR. This does not fix the fake node problem, I can still create one, for various reasons. Fixing the problem means that no one is able to maintain fake nodes.

> Let me explain it with an example so that even you can understand:

Again, a sneaky personal attack, which just shows your true colors, even though I asked to stop with this kind of things.

Anyway, let's stay on topic. People will still compete for the best hash which will result in tx spam for every arbitrage opportunity. Of course, no one is that stupid to compete with 1 lottery ticket. You might have 50 people, each one running a few hundred machines to compute a hash, and then try out their luck with 3-4 txes. This will be about 200txes in total per arb. You don't need to be 100% sure on your hash to make profit.

Let's assume there are just 2-3 players having 99% hashpower, like you sustain in your example. Obviously this will not be the case in the real world, but let's stick with it. They will always win, and no one will compete, so there will be no spam. This sounds really bad.  You reduce everything to a network efficiency problem, which is kind of stupid. Efficiency is a feature, not the purpose. This is a trading platform, the purpose should be to offer a reasonably fair competition to anyone, even if it's costly for the network at times. There shouldn't be one party at the top with all the hash power in the world, and no one competing. But hey, now we have a 100% efficient network, with 0 competion, that no trader/investor will use anymore, great! 

This is just going by your example, but I don't think that there won't be competition (and spam) anymore.

2022-05-28 19:05 UTC, lennybakkalian commented
> This does not fix the fake node problem, I can still create one, for various reasons.

which would be?

> Again, a sneaky personal attack, which just shows your true colors, even though I asked to stop with this kind of things.

of course i will get personal at some point if you don't read through previous comments and repeat things.
here is a good example:

>Another important thing: Ethereum actively decided against this. No other network uses this sorting for good reasons.

this point has been discussed twice now, but because you and some others are too lazy to read through previous comments, we always go around in circles here. this PR now has more than 100 comments and I guess 80% of them are repeated things.

if you want to contribute to this PR, please read ALL the comments and stop complaining that i will get personal about it.

> Efficiency is a feature, not the purpose. This is a trading platform, the purpose should be to offer a reasonably fair competition to anyone, even if it's costly for the network at times. 

you are mixing two things here: normal traders and mev participants. trading can and should be done fairly by everyone. mev trades can't be done by everyone. and we shouldn't focus on making this particular area "fair" because the tradeoff is way too big. fake nodes slow down syncing and tx/block forwarding.

2022-05-28 19:26 UTC, TxByTime commented
The fact that this single entity migrated to a new contracts is actually a great opportunity to gather some data on how much they actually spam and provided me a reason to make another post:
0x270eb2621eb213a0600a03151af8f9be520e56d4 30.000 txs
0xfbaebcb3c22ba9acb3a64eb0be82c9a46c56deea 30.000 txs
0x3f32d3eaabdcb3a9fe8101e58cf40621b7d43e15 30.000 txs
0x911c6f41f62ae50277dcd2254753bc832aab904b 28.000 tx
I got this data from bscscan when the contracts were 3 days old. That means this entity used about 120.000 txs in three days. This is about 40.000 tx per day out of a total of 4.5 million tx per day on bsc. Thats not even a single percent and only about 1.4 tx per block. Even if this PR would get rid of 100% of them, which it wont, it would be barely noticed. So this PR will not have no affect on blockspace when you consider that even a successful tx only needs about 200k gas out of 80 million blockspace. 

I have already explained why this PR will not get rid of these fakes nodes: We have already established that this PR will not get rid of PGA's. The whales will still need these nodes to be able to compete against other whales for their PGA strategies. And they might still use them for the backrun strategys if it gives them some advantage like hidding their tx with the best hash or waiting until the last possible moment to sent their tx.

It seems that finally most here now agrees that this PR will not level the uniswap arbitrage playing field and will only benefit the big whales.

I agree that the BSC maintainers should just decide what to do. But they should consider that:
No other chain running on geth, even those with worse tx spam situation like polygon are discussing tx order by hash. Ethereum, with a lower tx/s capacity and blockspace to absorb spam as bsc has decided against it two years ago. https://github.com/ethereum/go-ethereum/issues/21350 https://github.com/ethereum/go-ethereum/pull/21358
The txs might be cheaper on bsc, but the rewards are greater on Eth and spam is still a problem there. Just look at this: https://etherscan.io/txs?block=14804516&ps=100&p=3. Hint: Look for MEV Bot labels, but not every bot will have them.

2022-05-28 22:09 UTC, henopied commented
I found some more [discussion](https://github.com/ethereum/pm/blob/master/AllCoreDevs-Meetings/Meeting%2093.md#4-how-transaction-selection-happens-in-a-client-at-the-moment) by the Ethereum devs about this ordering. They all seemed to agree on the path forward and were clearly _against_ this kind of transaction ordering for reasons that would be equally applicable on BSC or ETH. In fact, a dev commented about how this created an exploit during an ICO when Parity/OpenEthereum had this ordering. It has been suggested, tried, and failed. I see no compelling reason to implement this order.

If the problem is fake nodes, we should ask what problem we want to solve. Do these nodes make it harder to sync? If this is the primary concern, enforcing nodes to respond to requests for data will improve syncing. Even if fake nodes proxy data requests, they will allow other nodes to stay synced. However, I doubt this is an issue because there should already be a checkpoint challenge system for ensuring peer nodes are in sync when the node is out of sync. This mechanism might need to be tested to ensure it works as intended, but if it does, then these nodes should not make it harder to sync. Anyways, passing your requests will increase your bandwidth so some operators may prefer to keep an actual node. Perhaps we should cherry-pick ethereum/go-ethereum#24652. Additionally, we could try to (maybe with help from the eth team) create a system where you can prove knowledge of the chain in a way that can't be proxied (probably involving some proof with chain data and your pubkey.)

As an aside, I find it extremely disingenuous that you impugn others' motives on this thread when it's very clear that you are also "in the game" and have failed under the current regime, so you try to change it for your benefit, to the detriment of BSC users. You will quickly find that bot operators like @ModifiedGeth will benefit from this change as they can outcompete you on hashpower. You probably won't even get a small profit because you will lose money on failed transaction costs.

Not really sure if anyone here cares, but this system will have a clear environmental impact as we would create a PoW MEV system with top players dumping millions into power consumption.

2022-05-28 23:01 UTC, lennybakkalian commented
> I found some more [discussion](https://github.com/ethereum/pm/blob/master/AllCoreDevs-Meetings/Meeting%2093.md#4-how-transaction-selection-happens-in-a-client-at-the-moment) by the Ethereum devs about this ordering. They all seemed to agree on the path forward and were clearly against this kind of transaction ordering for reasons that would be equally applicable on BSC or ETH.

interesting dialogue. I would, however, like to draw your attention to the last two sentences of the discussion you linked to.
I have attached the complete message: 

> Peter Szilagyi: We can definitely investigate different sorting methods, it doesn't really matter as long as it's deterministic. The other two proposals, sorting by transaction hash allows it to be mined, and sorting by account hash or addess also has a negative effect on the chain, that people will start to mine accounts, and weird things that someone left their GPU miner on it for a week and now has a priority in all transactions. **I didn't like these approaches, which is why we went with firs in first out, the worst you can do is try to find a direct connection to the miners, or miners could sell a direct connection. At that point, they may as well sell priority regardless.**

> for reasons that would be equally applicable on BSC or ETH

ethereum (POW) and BSC (PoSA) differ in that they are centralized in 21 places. therefore, i would not assume that bsc should be viewed the same as ethereum. locating these 21 validators is easier than with ethereum, where anyone can be a miner. of course i don't want to pick cherry, and his message also says that he doesn't want it to be deterministic. 

> how this created an exploit during an ICO when Parity/OpenEthereum had this ordering.

what kind of argument is that supposed to be? not developing a feature just because it triggered a security vulnerability does not mean that this feature is something bad. Sorry but this is a strange way of argumentation...

> Anyways, passing your requests will increase your bandwidth so some operators may prefer to keep an actual node.

bandwidth is cheaper than nvme space with RAM and CPU it takes to run a full node. running a fake p2p node is extremely cheap. And if the state needs to be verified, then the fake p2p server simply connects to a full node to query the state there. As I said, the goal should not be to detect the fake nodes because you can always work around that.

> As an aside, I find it extremely disingenuous that you impugn others' motives on this thread when it's very clear that you are also "in the game" and have failed under the current regime, so you try to change it for your benefit, to the detriment of BSC users.

What's wrong with being transparent? I could just as well keep my personal interests secret. Of course, after this PR, I will no longer have a chance in the MEV game, but I don't care. I'm just upset that new accounts are constantly created and (roughly summarized) say: this PR makes their mev bot broken or that then mev opportunities are unfairly distributed. This PR was created primarily to reduce fake nodes and spam tx as well as pending tx spam significantly.

2022-05-29 00:01 UTC, MrSonicMaster commented
@lennybakkalian 

> ethereum (POW) and BSC (PoSA) differ in that they are centralized in 21 places. therefore, i would not assume that bsc should be viewed the same as ethereum. locating these 21 validators is easier than with ethereum, where anyone can be a miner. of course i don't want to cherry picking, and his message also says that he doesn't want it to be deterministic (for ethereum pow).

I would disagree - ethereum has flashbots which is essentially a service which provides a deal with many miners/mining pools. This essentially makes ethereum and bsc virtually identical in terms of how feasible and beneficial a deal with miners/validators would be.

> > how this created an exploit during an ICO when Parity/OpenEthereum had this ordering.
> 
> what kind of argument is that supposed to be? not developing a feature just because it triggered a security vulnerability does not mean that this feature is something bad. Sorry but this is a strange way of argumentation...

If a piece of code is known to have an exploit, how can it possible "not mean that this feature is something bad"? Any code that is known to have caused exploits in the past is undeniably bad and should not be implemented. Perhaps I'm misunderstanding what you're trying to say here.

> bandwidth is cheaper than nvme space with RAM and CPU it takes to run a full node. running a fake p2p node is extremely cheap. And if the state needs to be verified, then the fake p2p server simply connects to a full node to query the state there. As I said, the goal should not be to detect the fake nodes because you can always work around that.
> 
> >

Yes, bandwidth is cheaper than NVMe space, and perhaps they won't switch to running full nodes - but you're missing his point. After they "connects to a full node to query the state there" and relay the response to the requester, the issue that fake nodes cause will be solved. Now people who are connected to them will be able to sync from them. This solves the main argument against "fake nodes" - now they will be just as beneficial to the network as any other node.

> What's wrong with being transparent? I could just as well keep my personal interests secret. Of course, after this PR, I will no longer have a chance in the MEV game, but I don't care. I'm just upset that new accounts are constantly created and (roughly summarized) say: this PR makes their mev bot broken, that then mev opportunities are unfairly distributed or repeat arguments that have already been used x times.. This PR was created primarily to reduce fake nodes and spam tx as well as pending tx spam significantly.

Unfortunately this PR both centralizes MEV AND does nothing to solve fake nodes or spam txns, which is why so many people are arguing against it. Even bertcmiller, one of the creators of flashbots, agrees that this PR will [only transition the spam into another form of priority auction](https://twitter.com/bertcmiller/status/1529912367936589835). Fake nodes & deals with validators will continue to be encouraged for latency benefit and better access to pending txns so they can view the competition.

2022-05-29 10:11 UTC, 48ClubIan requested changes
This is practically turning BSC into PoW.

Hash power will be the new gas price, people don't need to pay the higher gas prices for priority anymore, they mine better positions instead. 

If I am an ETH miner I would love to vote for this, so that my machines will be able to keep making money after ETH 2.0 , oh wait maybe I should submit a PR myself. Ruing validators and stakers benefit? None of my business.

2022-05-29 10:11 UTC, TxByTime commented
@lennybakkalian

>ethereum (POW) and BSC (PoSA) differ in that they are centralized in 21 places. therefore, i would not assume that bsc should be viewed the same as ethereum. locating these 21 validators is easier than with ethereum, where anyone can be a miner.

Anyone could become a miner on eth, but that doesn't mean that they will ever mine a block. If anyone wants to have an actually chance of ever mining an Eth block they have to join a miningpool. If you take a look at https://etherscan.io/stat/miner?range=1&blocktype=blocks you will see that mining on Eth is also centralized. The Top 25 mining pools mine close to 98% of all blocks - the best and openly corrupt one mines even more than 25% at the time of this writing. As I have said before: Eth and Bsc are not that different.

2022-05-29 10:54 UTC, cwazy2020 commented
> This is practically turning BSC into PoW.
> 
> Hash power will be the new gas price, people don't need to pay the higher gas prices for priority anymore, they mine better positions instead.
> 
> If I am an ETH miner I would love to vote for this, so that my machines will be able to keep making money after ETH 2.0 , oh wait maybe I should submit a PR myself. Ruing validators and stakers benefit? None of my business.

This isn't correct though.  It's sort by price and hash.  So higher price means you still get priority.  This literally only affects backrunning.  Why are you spreading FUD?

2022-05-29 11:07 UTC, ktrout1111 commented
@MrSonicMaster 

> Yes, bandwidth is cheaper than NVMe space, and perhaps they won't switch to running full nodes - but you're missing his point. After they "connects to a full node to query the state there" and relay the response to the requester, the issue that fake nodes cause will be solved.

Just to add some clarity here - a few months ago when I did my analysis and found the hundreds of fake nodes belonging to the same bot operator, I noticed they were apparently also running a much smaller number (4 maybe?) of full nodes. This makes sense. Fake nodes need verified validated data or they might get trolled by fake mark txs. So it looks like the big players run "supernodes" that all the smaller "fake" nodes rely on for information.

> Now people who are connected to them will be able to sync from them. This solves the main argument against "fake nodes" - now they will be just as beneficial to the network as any other node.

Why would fake nodes bother being of service like this? It would cost them CPU and bandwidth to be good citizens.

2022-05-29 11:09 UTC, ktrout1111 commented
@48ClubIan 

> Hash power will be the new gas price, people don't need to pay the higher gas prices for priority anymore, they mine better positions instead.

Why would anyone bother with this when they could just add an extra 1 Wei to their gas price? A single hash probably costs more electricity than doing that. Surely you don't expect anyone to believe such a flimsy argument.

2022-05-29 11:47 UTC, TxByTime commented
[ktrout1111](https://github.com/ktrout1111)

>>Now people who are connected to them will be able to sync from them. This solves the main argument against "fake nodes" - now they will be just as beneficial to the network as any other node.

>Why would fake nodes bother being of service like this? It would cost them CPU and bandwidth to be good citizens.

[henopied](https://github.com/henopied) was suggesting that nodes that don't provide this service should get dropped. If all fake nodes were to be dropped they would be of no use for the operators. It would either get rid of them or force them to be a good citizens. Didn't you read their suggestion?
And like [MrSonicMaster](https://github.com/MrSonicMaster) has already pointed out: It does not matter if they get the data from a real fullnode or actually have it. They will still have to send real data to other nodes and therefore improve the network or risk getting dropped.

2022-05-29 11:48 UTC, MrSonicMaster commented
> > Now people who are connected to them will be able to sync from them. This solves the main argument against "fake nodes" - now they will be just as beneficial to the network as any other node.
> 
> Why would fake nodes bother being of service like this? It would cost them CPU and bandwidth to be good citizens.

I hate that we all have to be such broken records here. I'll refrain from further polluting this discussion with more repeats of the same arguments and instead ask that you fully read the chain of comments that led to this statement.

2022-05-29 12:27 UTC, 48ClubIan commented
> > Hash power will be the new gas price, people don't need to pay the higher gas prices for priority anymore,
> 
> This isn't correct though. It's sorted by price and hash. So higher price means you still get priority. This literally only affects backrunning and might have some mild effect on PGAs. It's literally in the function name, which is "TxByPriceAndHash". Why are you spreading FUD?

If you keep calling anything you don't agree to a FUD, I don't see any point you should join this discussion.

I am pointing out a possibility against my interest, and yes of course it is possible. People make their own decisions on paying more gas or mining a hash, it's a good chance for mining to be cheaper.

2022-05-29 12:31 UTC, 48ClubIan commented
> @48ClubIan
> 
> > Hash power will be the new gas price, people don't need to pay the higher gas prices for priority anymore, they mine better positions instead.
> 
> Why would anyone bother with this when they could just add an extra 1 Wei to their gas price? A single hash probably costs more electricity than doing that. Surely you don't expect anyone to believe such a flimsy argument.

Simple, adding 1 gwei is not absolutely cheaper than electricity for mining the hash. It's not as "probably" as you can easily say it without any evidence.

Or let me ask this way, "Why would anyone spam their tx when they could just add an extra 1 Wei to their gas price? "

2022-05-29 12:38 UTC, ktrout1111 commented
> [henopied](https://github.com/henopied) was suggesting that nodes that don't provide this service should get dropped. If all fake nodes were to be dropped they would be of no use for the operators

This is of course a good idea, but how to implement it? It was conceded in the original Eth discussion that this would be a necessary evil of switching to sorting by time, as it's easy for a fake node to pretend to be a full one.

> And like [MrSonicMaster](https://github.com/MrSonicMaster) has already pointed out: It does not matter if they get the data from a real fullnode or actually have it. They will still have to send real data to other nodes and therefore improve the network or risk getting dropped.

So how would this be implemented? I'm not against the idea at all, it's obviously a good one - but what does the implementation look like? During my analysis I found many "types" of apparently fake nodes, and had to use some very ugly, inaccurate heuristics to detect them, and even those often fell short. What criteria would we impose upon a node in order to accept it as "real"? 

If we set the bar at "it must eagerly spam block headers when it receives them, and must respond with block bodies when requested", that would only be a minor inconvenience to the whales, since a block body is only a few hundred kB of data every 3 seconds. They would be fed the data from their "supernodes" that I mentioned earlier, or maybe from a validator.

OK, so what if we add the extra criteria: "it must accurately and honestly distribute pending tx hashes and bodies (to a sqrt of peers) as and when it receives them." Two problems here: 1) The existence of the DisablePeerTxBroadcast config flag (which IMO is a terrible "feature") means that the devs apparently don't even consider broadcasting txs to be an important feature of a full node! So we can't require something that the devs have already decided isn't required. 2) How would we define adherence to this rule? Even a centralised way of enforcing it would be extremely difficult, let alone a decentralised one that any node can use. Again, it would have to be some ugly heuristic, and I can't even think how it would be implemented.

I'm open to better ideas of how to implement this idea that I might have missed, but on cursory inspection it doesn't look feasible. As @lennybakkalian has pointed out, better to remove the incentive for running fake nodes than trying to tackle the problem directly, IMO.

2022-05-29 12:39 UTC, lennybakkalian commented
> After they "connects to a full node to query the state there" and relay the response to the requester, the issue that fake nodes cause will be solved. Now people who are connected to them will be able to sync from them.

this assumption is completely wrong. you are talking about request/response syncing here. But that's not how eth p2p works. Do you want to query blocks & txs blindly from a node? If some nodes are a few minutes behind and don't have this information, what should happen? Currently a node only requests information where it knows that the peer has it and that should not have changed. What you are proposing is a deep intrusion into the p2p protocol which should not be enforced at all. 

> Simple, adding 1 gwei is not absolutely cheaper than electricity for mining the hash. It's not as "probably" as you can easily say it without any evidence.

maybe you should read correctly: he said 1wei. hardware to calculate hashes is more expensive than adding 1 wei in a tx

2022-05-29 12:40 UTC, ktrout1111 commented
> Simple, adding 1 gwei is not absolutely cheaper than electricity for mining the hash. It's not as "probably" as you can easily say it without any evidence.

I said 1 WEI, not GWEI. 1 quintillionth of a BNB per unit of gas. Cheaper than second-hand pocket lint. It may or may not be cheaper than one single hash. I used this example to illustrate how insane your argument is.

2022-05-29 12:54 UTC, 48ClubIan commented
> > Simple, adding 1 gwei is not absolutely cheaper than electricity for mining the hash. It's not as "probably" as you can easily say it without any evidence.
> 
> I said 1 WEI, not GWEI. 1 quintillionth of a BNB per unit of gas. Cheaper than second-hand pocket lint. It may or may not be cheaper than one single hash. I used this example to illustrate how insane your argument is.

Fine, I will forgive you for not knowing the prisoner's dilemma and believing you are the only one who is able to add gas prices.

2022-05-29 12:56 UTC, 48ClubIan commented
> > After they "connects to a full node to query the state there" and relay the response to the requester, the issue that fake nodes cause will be solved. Now people who are connected to them will be able to sync from them.
> 
> this assumption is completely wrong. you are talking about request/response syncing here. But that's not how eth p2p works. Do you want to query blocks & txs blindly from a node? If some nodes are a few minutes behind and don't have this information, what should happen? Currently a node only requests information where it knows that the peer has it and that should not have changed. What you are proposing is a deep intrusion into the p2p protocol which should not be enforced at all.
> 
> > Simple, adding 1 gwei is not absolutely cheaper than electricity for mining the hash. It's not as "probably" as you can easily say it without any evidence.
> 
> maybe you should read correctly: he said 1wei. hardware to calculate hashes is more expensive than adding 1 wei in a tx

It doesn't change anything, 'cause it doesn't depend on a single tx sender that how big a raise will effectively work.

2022-05-29 13:09 UTC, TxByTime commented
[ktrout1111](https://github.com/ktrout1111)

>So how would this be implemented? I'm not against the idea at all, it's obviously a good one - but what does the implementation look like? During my analysis I found many "types" of apparently fake nodes, and had to use some very ugly, inaccurate heuristics to detect them, and even those often fell short. What criteria would we impose upon a node in order to accept it as "real"?

Have you actually read the suggetion from [henopied](https://github.com/henopied)? He already provided some information on how this implemation would look like. Could you please point out what he might have missed or some flaws in that idea? 

>As @lennybakkalian has pointed out, better to remove the incentive for running fake nodes than trying to tackle the problem directly, IMO.

This PR does not remove the incentive to remove these fake nodes. They gain the same advantages from them for their PGA strategies as their backrun strategies. They will still be there if it gives them any advantage for there. You seem to ignore this argument. If they cause users to get out of sync, force the nodes to help them sync or drop them base on the suggestion from [henopied](https://github.com/henopied)

2022-05-29 13:33 UTC, lennybakkalian commented
> If they cause users to get out of sync, force the nodes to help them sync or drop them base on the suggestion from [henopied](https://github.com/henopied)

also i think we are talking about two different points here. the fake nodes don't care about peers that are not yet fully synced, since they don't forward txs anyway (as i understand it). and after a peer becomes a full node, we [shouldn't force other peers to send blocks or txs](https://github.com/bnb-chain/bsc/pull/915#issuecomment-1140441100), since i can well imagine that this will make the network unstable since never all nodes are equally synced.

you can give as many implementation ideas as you want, but detecting fake nodes (which can't be bypassed) and without running the risk that the current network suffers from it will be difficult and in my opinion impossible, which is why we should remove the incentive to want to run such a fake node altogether.

> They gain the same advantages from them for their PGA strategies as their backrun strategies. They will still be there if it gives them any advantage for there. You seem to ignore this argument.

there is no argument if you do not describe it. simply saying: they use fake nodes for "PGA strategies" is not an argument

2022-05-29 13:41 UTC, lennybakkalian commented
## To all participants:

what do you think if each side summarizes their arguments and counter-arguments, posts them here and then there is no further discussion until a bsc maintainer is there. this PR is much too big to have an overview of arguments here

2022-05-29 13:41 UTC, lennybakkalian commented
## To all participants:

what do you think if each side summarizes their arguments and counter-arguments, posts them here and then there is no further discussion until a bsc maintainer is there. this PR is much too big to have an overview of arguments here

2022-05-29 14:35 UTC, MrSonicMaster commented
> there is no argument if you do not describe it. simply saying: they use fake nodes for "PGA strategies" is not an argument

First I will point out that he should not need to describe it - it has already been described many times here. But let me reiterate it once more, and pray that it will actually be read in full. I feel that this will also serve as an overview of counter-arguments as you have asked for, and a collection of ideas that I believe to be better for BSC than this PR.

So lets play this idea out. So I'm running a bot, and this PR is successfully merged. Now I must switch my strategy to mine for best hashes (which of course goes without saying that it has negative impact to environment, and honestly would be a huge regression for DeFi). So I mine a decent hash, submit it using my connection to validator and/or network of fake nodes to gain latency advantage, and wait. Then - oh no! Using my network of fake nodes to gain a larger presence and low-latency access to the mempool, I'm able to see that a better hash has been submitted by a competitor. Now I must mine another hash, submit it, and - oh, well now both my transactions will land on-chain. Why? Because once the txn has gotten far enough on its way to validator, it can only be replaced by fee bump. As this PR pushes for hash sort only for same gas price, fee bump will not be possible if we want txn to order before/after a trigger txn of set gas price - so a completely new txn must be submitted. Yes as better and better hashes are found this will become exponentially slower, but perhaps will iterate a couple times per opportunity amongst all the bots. This is the new form of priority auction that this PR will cause and inherently will still incentivise fake nodes to gain a latency & txpool advantage, while also worsening the issue of spam by causing every 'better' transaction to actually land on-chain, rather than only existing in mempool. Now we have an even worse issue - more blockspace is taken up by botting, while still having the issue of incentive for fake nodes, and incentive to connect to or make deals with validators.

And, of course, this PR would also centralize MEV among those with the most money. Even if I can buy 1% of total hashrate, I will waste so much on gas fees during the 99% of fails in futile attempts to beat whales that it will not be feasable to attempt this. Maybe one could argue that I can 'sit out' of opportunities if I see that someone already has better hash, but how will I have any chance to know this without my network of fake nodes to cheaply gain large presence and low latency access in mempool? And maybe whales have direct connection/deal with validator, and can afford to wait a second or two before submitting their transaction. As arrival time no longer matters, they can afford to wait long time to get best hash before submitting. Perhaps I, the small fish, do not have this luxury and will see it only after I have submitted my txn earlier and inevitably wasted money on gas fee.

It becomes quite clear that this PR will only worsen the situation on BSC, and a better solution must be implemented instead.

[In p2p 'eth' subprotocol](https://github.com/ethereum/devp2p/blob/master/caps/eth.md), peers are supposed to advertise hashes of block headers, bodies & txns that they are aware of, and under official spec can be penalized if they refuse to honor this at a later time. A very simple enforcement that peers must consistently advertise & honor these can go a long way. Something like this overview:

td: means total difficulty, measurement of how synced they are. 

-if the remote node is < your td on connect, ignore txns from them (they aren't synced and can't possibly have validated the txns they're sending - will stop us from helping 'fake nodes' send their spam txns) and help them to sync if they ask for it. if they don't ask for it after X time has passed, kick them and put them in timeout. We aren't clearly helping them sync and they aren't helping us, no point to be connected.
-if the remote node is synced (their td >= our td), and they never advertise block bodies or headers, or repeatedly refuse to reply with helpful data on request when they had advertised that they know it, then kick them & put them in timeout for X amount of time. They don't need help syncing, and aren't helping us at all so why stay connected. This forces the "spam bots" to serve data that benefits the network, and stops the issue where half of peoples peers are not helping them to sync. 

Such ideas obviously require a lot of thought and testing before they can be implemented, and would require a commitment from a team of smart people. Most likely this idea would need to be entertained by core bsc developers, but I feel as though this is a solid "starting point" to get the mind going.

I will also once again quote henopied's similar ideas on the subject:

> If the problem is fake nodes, we should ask what problem we want to solve. Do these nodes make it harder to sync? If this is the primary concern, enforcing nodes to respond to requests for data will improve syncing. Even if fake nodes proxy data requests, they will allow other nodes to stay synced. However, I doubt this is an issue because there should already be a checkpoint challenge system for ensuring peer nodes are in sync when the node is out of sync. This mechanism might need to be tested to ensure it works as intended, but if it does, then these nodes should not make it harder to sync. Anyways, passing your requests will increase your bandwidth so some operators may prefer to keep an actual node. Perhaps we should cherry-pick [ethereum/go-ethereum#24652](https://github.com/ethereum/go-ethereum/pull/24652). Additionally, we could try to (maybe with help from the eth team) create a system where you can prove knowledge of the chain in a way that can't be proxied (probably involving some proof with chain data and your pubkey.)

(Though I hate to again repeat the discussion, I feel that to prevent unnecessary repetition in further comments I must quickly repeat this here. The quote that "your requests will increase your bandwidth so some operators may prefer to keep an actual node" has been discussed, and I would agree that it is likely that they will not switch to full nodes over 'fake nodes,' but regardless would be forced to make their "fake nodes" helpful to the network if such a system was put in place.)

I feel like the focus should be shifted to perfecting ideas such as these, as such ideas will be far more helpful to BSC and will not have the major downsides that this PR imposes.

2022-05-29 15:58 UTC, TxByTime commented
In addition to the post of [MrSonicMaster](https://github.com/MrSonicMaster) i want to add:

### Why it should not me merged:

### Why it won't significantly reduce tx spam:
I have shown here https://github.com/bnb-chain/bsc/pull/915#issuecomment-1140317864 that this bot thats accused of sending hundrets of tx per opportunity is actually only sending about 1.4 tx per block on an average day at about 300k gas out of 80m block space. This is not spam.
This 1.4tx per block would not even be completly removed. As has been pointed out, there might still be spam each time a better hash is found.
There is no prove from the other side that tx spam or blockspace is actually a problem affecting the BSC network.
BAS will free up even more block space. 

### Why it won't get rid fakes nodes:
What this PR claims they are: "fakes that only exist to flood the network with their own arb txs and censor all other txs and block data"
The winner of a backrun is whoever has his tx first at the validator. The winner of a priority GAS auction (PGA) is whoever has the highest priced tx at the validator during block constructions. Any advantage these fake nodes might give bot operators for their backrun strategies (get a target tx faster, sending fake nonce tx, censor other tx, getting it faster to a validator) also apply to PGA strategies. We have already established that this PR will not get rid of PGA's. This means the whales will still need these nodes to be able to compete against other whales for their PGA strategies and this PR would not remove any of them. I apologize if I do a bad job of explaining PGA's here. I would be willing to explain it to the BSC maintainers in private if they have any question regarding this argument or strategy. I'm obviously not leaking everything about this on a public forum.

The fake nodes will also still be there if it gives some advantage for backrun strategies: flood the network with fake transactions, censor a better hash of a competitor, send a tx to the validator at the last possible moment, give a few ms more time to mine hashes and maybe some other adverse methods we are currently unaware of.

The real extent of this problem is unkown: no one has provided any actual or recent data on how many of these might exist.
If there is actual proof of this being a serious concern: There are different suggestions here on how it would force them to be good citizens.

### Why it won't significantly reduce fake nonce tx spam:
What are they? Same nonce tx with the same sender, but some difference (gasPrice, data, gasLimit) and different hash.

Any advantage these might give bot operators for their backrun strategies also apply to PGA strategies. Like above, I can explain more details about PGA to the maintainers in private.

They will also still be there for backrun strategies: 
Whales will use them to show the competition a tx with a worse hash than what they actually already have at the Validator. This is to confuse them about their actual tx with a better hash and to get the competition to submit a tx with a hash that would not be good enough. This type of strategy is called draining of inventory and something similar is already happening - I will only share details about this with the BSC maintainers in private.

### Why it will not level the uniswap arbitrage playing field:
Only the big whales with most of the hashpower would be able to compete. The whales will be able to rent ASICS mining farms from their past profits. No new player will be able to enter the game. Any small player that can currently compete would not have a chance anymore. 
These small players exist, even if the other side claims that is impossible. I can share some of these small players making about 10k/month to the BSC maintainers in private. I will not leak them on this public forum, since this would lead to them being copied and destroyed.

### Ethereum decided against this two years ago
Eth and BSC are not that diferent in term of centralization: https://etherscan.io/stat/miner?range=1&blocktype=blocks The Top 25 mining pools mine close to 98% of all blocks - the best and openly corrupt one mines even more than 25% at the time of this writing. Locating these 25 is just as simple as locating the 21 Validators on Bsc.

No other chain running on geth, even those with worse tx spam situation like polygon (https://github.com/maticnetwork/bor/pull/292) are discussing tx order by hash. Ethereum, with a lower tx/s capacity and blockspace to absorb spam as bsc has decided against it two years ago. https://github.com/ethereum/go-ethereum/issues/21350 https://github.com/ethereum/go-ethereum/pull/21358 Apparently some of the discussion was held in the Ethereum devs discord or other forums and not everything regarding this is on github. Some of it can be found here: [discussion](https://github.com/ethereum/pm/blob/master/AllCoreDevs-Meetings/Meeting%2093.md#4-how-transaction-selection-happens-in-a-client-at-the-moment).

### It turns part of BSC into a POW network

If someone wants to add something here, you are free to contact me.

2022-05-29 18:03 UTC, lennybakkalian commented
*I will now summarize my view of this PR for the last time. Perhaps I will respond with references to this comment, but no longer argue because we are going around in circles anyway.*


## Why i think this PR should be merged (my personal summary)

### 1. Resolves pending tx spam
- txs with the same nonce and gas price but with a different hash are spammed in the p2p network, because full txs are only forwarded to a handful of peers due to (peers/sqrt) in order to reach the validator as early as possible. after this PR hashes would have to be mined outside the network to influence the sorting, which would make spammed pending txs unnecessary.

### 2. Resolves unique tx spam (for arb mev at least)
- currently several txs from different addresses are sent to the same contract for an arb trade (also in the hope to land as early as possible at the validator similar to pending tx spam).
- with this method, exponentially fewer txs would be sent out by an arb trader, as it becomes harder and harder to find a better hash. also, it would make no sense to send out a tx right after an arb opportunity, as that hash will be outbid by the competition anyway. and as it becomes exponentially harder to find a hash, there will end up being only a handful of arb trades.

I would like to quote a comment from @ktrout1111 at this point.
> You and others have repeated this, implying it is a rapid, regular thing, like machine gun fire, when in fact the rate at which a better hash occurs for any given miner decreases  _exponentially_  with time. This is even without taking into account the extra diminishing effect of listening to the mempool for the current  _global_  best hash. This is easy to prove. At the beginning of each "game" the probability of the next hash being lexicographically after the mark tx is p0 = (b0 - m) / (2^256), where m is the hash of the mark tx, and b0 is the current lowest known tx hash greater than m.
>How b0, and thus p0, is determined is somewhat hazy but also irrelevant since bot operators will heuristically determine a realistic threshold distance (b - m) value that must be achieved before they send any txs. So let's say p0 = 0.001. Once they find a hash better than b0 - let's call it b1, they may or may not spam a tx (they will hold fire if the global best hash in the mempool is already better than theirs). Now, b1, by definition, has landed uniformly randomly in the interval (m, b0). This means, on average, the probability of subsequent hashes (b2) being better than b1 has now been  _halved_. In extreme cases the probability might only be shaved by 1% or by 99%, but amortised over time, the probability is halved each time a better hash is found, damping any spam exponentially over time.

### 3. Resolves fake nodes
- fake nodes are currently used to bring own txs as fast as possible into the network (because of the arrival time sorting) to have the few ms advantage. 
Q: *why should fake nodes be a problem at all?*
A: because these do not contribute anything to the network and only consume resources & peer slots which makes syncing blocks and pending txs slower because these nodes do not forward anything.
Q: *then just have fake nodes recognized and kicked as a peer?*
A: this will not be possible. Fake node operators will always find a way around it. 
Q: *but then we verify the blockchain state or if this peer does not send new information after x seconds/minutes he will be kicked as useless.*
A: will not work either, because the fake nodes know about the latest state via a "supernode" and can thus avoid verification. also, this change could lead to peers who often go out of sync (due to e.g. bad hardware) not being able to participate in the network anymore, because they are kicked again and again for not contributing anything new (but still strengthening the network and thus not being useless). running full nodes would therefore become more expensive which could lead to less people running a full node.

- our goal should not be to recognize fake nodes, but to take the reason to run them! otherwise it becomes a game of cat and mouse

### 4. Ethereum devs were against tx hash sorting
- someone had once linked [this](https://github.com/ethereum/pm/blob/master/AllCoreDevs-Meetings/Meeting%2093.md#4-how-transaction-selection-happens-in-a-client-at-the-moment) where the eth devs discuss it:
>**Rai**: Is the consensus to sort by arrival time?
>**Alexey Akhunov**: It seems like the simplest option with few downsides.
>**Peter Szilagyi**: We can definitely investigate different sorting methods, it doesn't really matter as long as it's deterministic. The other two proposals, sorting by transaction hash allows it to be mined, and sorting by account hash or addess also has a negative effect on the chain, that people will start to mine accounts, and weird things that someone left their GPU miner on it for a week and now has a priority in all transactions. I didn't like these approaches, which is why we went with firs in first out, the worst you can do is try to find a direct connection to the miners, or miners could sell a direct connection. At that point, they may as well sell priority regardless.

- it also says here that they are against deterministic sorting, but that it would also be bad if the miners are searched for.
Q: ok if ethereum is against hash based tx sorting then we should not do that either.
A: but eth (POW) and bsc (PoSA) are completely different. bsc is centralized in 21 places and thanks to the cheap tx costs you can spam txs.
Q: well then this PR provides again for POW what hurts the environment.
A: POW would be made only by the arb traders and only so much that they outbid the competition. Unfortunately, I do not want to and can not name any numbers here because I am not so deep in this subject. But I know one thing: to operate fake nodes and to generate extra effort for full nodes is also not environmentally friendly. Maybe there is someone here who can give numbers how bad this aspket would be.

### 5. MEV
- **I myself am not a MEV whale and therefore, like everyone else in this PR, can only answer with limited knowledge:** 
- MEV is currently very centralized as has been described and confirmed many times in the PR. It cannot be more centralized. the big players will always have more nodes, more hashpower, more everything
- these large mev participants are most likely connected directly or at most via 1 node (sentries) to the validator to send their txs milliseconds earlier to the validator.
- should it really remain so that only the mev participants who are connected to a validator have a chance? If so, then I'm happy to announce the scavenger hunt on validators! Will be interesting to see what will happen after validators are spammed with connection requests to get a free peer slot.

of course, this PR is not a cure for all problems, but it should be remembered if it turns out that it only improves one point and does not harm the BSC network.

I'm sorry if I haven't mentioned some of the counterarguments here, but this PR has become so confusing that I can't keep up. i will change this comment if there is any new insight

2022-05-29 21:33 UTC, berktaylan commented
Why dev team not making any comment on this case ?

2022-05-29 21:39 UTC, berktaylan commented
So some private companies already partnered with some validators ( 3 or 4 ) i think for private transactions. So no one cant believe me validators are fair and not changing/manipulating tx order. With this change we can review and confirm tx order and prevent manipulation.

Also ive seen some guys mentioned whales may pre compute hashes on bulk and use it regularly for backrun. This wont work since nonce , tx data and backrun gasprice changes dynamically. So they cant just pre compute hashes and use the txs from hash pool or something. Currently network is unhelathy, operating a binance node cost approx 700$ because of high performance I/O and nvme needs. That fakes nodes not even helping the security of the network and on top of that they are just congesting network with that spams.

2022-05-29 22:36 UTC, ktrout1111 commented
> Why dev team not making any comment on this case ?

They appear to have a code of silence on this matter (the MEV side of it anyway). The extreme centralisation of MEV on this chain caused by sorting by time has been mentioned in several other issues over the last year, and the contributors won't touch the issue with a 10 foot pole. It's all very mysterious.

2022-05-30 02:31 UTC, guagualvcha commented
The `Hash` can be brute-forced as long as you get enough hashrate,  so if the transactions are sorted by `Nonce->GasPrice->Hash`, it will cause hashrate competition, the result is that the big organization can always do both frontrun and backrun, it is easy to perform sandwich attack.

2022-05-30 02:36 UTC, guagualvcha commented
```
this way, arb bots will have 100% confidence about how txs will be ordered, thus instead of sending multiple txs, they "mine" the arbitration opportunities, which is even easier and more predictable.
```
Agree with @48ClubIan,

2022-05-30 02:43 UTC, guagualvcha commented
> I find it interesting that someone who works at a [validator finds hash based sorting bad](https://github.com/bnb-chain/bsc/issues/911). And someone else who works at 48Club downvoted the pull request without making any counterarguments. But anyway I have the feeling that half of all validators are corrupt and exploit MEV on their own because sorting is not traceable (just a guess).
> 
> I agree in all points with @ktrout1111
> 
> > this way, arb bots will have 100% confidence about how txs will be ordered
> 
> Currently i can assure that arb bots have a confidence of 99%. This is due to the spamming of transactions. Also, a corrupt validator can sort transactions as he wants without this being traceable.
> 
> A big point of the blockchain is also traceability, or would you (@48ClubSirIan) disagree with me? If someone wants to make a transaction without the arb bots finding it, they can use the "Direct-Route" of NodeReal. (Which in my opinion also sucks, because it breaks the decentralization and openness of the blockchain).

`But anyway I have the feeling that half of all validators are corrupt and exploit MEV on their own because sorting is not traceable (just a guess).`

--- This make no sense, if you have such feeling, what is the purpose of this PR?  The modification is for validators, is't it. Our team talked with most validators,  they did not sell special service except Nodereal,  and Nodereal limited the function of Direct  Route to provide only privacy rather than MEV in their latest update.

`If someone wants to make a transaction without the arb bots finding it, they can use the "Direct-Route" of NodeReal. (Which in my opinion also sucks, because it breaks the decentralization and openness of the blockchain).` 

---- Flashbots controls more than 40% hashrate, would you say Ethereum is not decentralized?

2022-05-30 09:53 UTC, lennybakkalian commented
@guagualvcha 
> This make no sense, if you have such feeling, what is the purpose of this PR? The modification is for validators, is't it?

those were secondary reasons (which was a personal assessment) but not the main reasons i had listed [here](https://github.com/bnb-chain/bsc/pull/915#issuecomment-1140497287)


> this way, arb bots will have 100% confidence about how txs will be ordered

but i think everyone here is also aware that currently every mev tx is sandwiched anyway. no matter if with or without this PR

2022-05-30 11:04 UTC, ktrout1111 commented
@guagualvcha 

> The Hash can be brute-forced as long as you get enough hashrate, so if the transactions are sorted by Nonce->GasPrice->Hash, it will cause hashrate competition, the result is that the big organization can always do both frontrun and backrun, it is easy to perform sandwich attack.

In order for a single entity to be confident they can pull this off, they would need nearly all of the hashrate, no? It's already known there are 2 or 3 big players, so if one has 40%, another 30%, and another 20%, with the remaining 10% made up by smaller players, then even the biggest whale has only a 0.4 * 0.4 = 16% chance of a sandwich attack not being sniped.

2022-05-30 11:56 UTC, MrSonicMaster commented
> but i think everyone here is also aware that currently every mev tx is sandwiched anyway. no matter if with or without this PR
> 
> >

Could you clarify what you mean here? In what way is every mev tx sandwiched already? What do you mean by "sandwiched" in this case?

> all traffic on direct route is routed through a domain belonging to a single validator. let's assume that all participants (so that they are not frontrunned for example) use this service: then nodereal would always have control e.g. which tx are forwarded to the other validators and which are not. so i conclude it's only a matter of how many people use this service before it becomes a problem. apart from the fact that you are forced to pay 20GWEI there because otherwise the tx is rejected (probably then that's the fee for this service). does this sound like decentralization if all txs run through one endpoint?

First, you appear to have misunderstood @guagualvcha's argument - all traffic for flashbots is routed through a domain belonging to one company, who can chose which txns to forward to the miners and which ones not to. Do you argue that eth is centralized? It seems you are trying to argue that nodereal on bsc is any different than flashbots on eth. In fact, nodereal can in some ways be considered more "fair" in the way that it does not provide help for sandwich bots (by requiring bundles must only have txns from same sender). 

You make the incorrect assumption in your example that "all participants use this service" - which is not true and never will be. There will always be other options, hence the title "decentralized." Not one company "controls" or "enforces" who you submit your txns to. You have the choice. If you want to have shielding from public mempool, you muse use directroute or flashbots services, and pay their fees. If you do not trust nodereal or flashbots to be fair in distributing your vs others txns then you may chose not use it - just like you may chose to run your own node, or trust the one hosted at bsc-dataseed.binance.org.

> In order for a single entity to be confident they can pull this off, they would need nearly all of the hashrate, no? It's already known there are 2 or 3 big players, so if one has 40%, another 30%, and another 20%, with the remaining 10% made up by smaller players, then even the biggest whale has only a 0.4 * 0.4 = 16% chance of a sandwich attack not being sniped.

I don't see how you conclude that that hashrate distribution has any relation to a sandwich opportunity not being sniped. With at least one person mining for it, every opportunity will be sniped by whoever had enough resources to win the competition. Unless, by pure chance, some other unrelated user submits a txn at just the right time to accidentally "beat" everyone - though such situations are negligible in probability.

@ktrout1111 
> How can they possibly have 100% confidence of the tx ordering?

How can they not have 100% confidence about ordering if the ordering is deterministic? What you are describing is not how txns will order within the block, but rather how probably it is that their hash is the "best" one submitted. Yes, maybe they will not know realtime if they have won the competition, but they will know that this will give them a deterministic approach - closest hash to trigger txn = win, 100% confidence. More hashrate = better win rate. Not even just more predictable, it is 100% predictable.

also @lennybakkalian I thought you were pushing for final comments to be put, then wait for bsc team to come and make their decision. Now we have done that, and bsc maintainer @guagualvcha has commented, yet we are still in debate? I feel this PR is now concluded, and should be closed in favor of better solutions.

2022-05-30 12:37 UTC, ktrout1111 commented
>  but they will know that this will give them a deterministic approach - closest hash to trigger txn = win, 100% confidence. 

Why is that a problem? This confidence (whether it is elicited by scanning the mempool or by porbabilistic modelling) is what would alleviate the current high levels of block spam.

> More hashrate = better win rate. Not even just more predictable, it is 100% predictable.

It's entirely unpredictable for any player to know ahead of time if they will win an arb. What are you talking about? All they know is their approximate probability of winning by calculating their relative hash rate. You could make the same argument about the current system - more nodes = better win rate. What's your point?

2022-05-30 12:48 UTC, lennybakkalian commented
> I thought you were pushing for final comments to be put, then wait for bsc team to come and make their decision.

I wasn't sure if @guagualvcha  had read my [summary](https://github.com/bnb-chain/bsc/pull/915#issuecomment-1140497287), as he was referring to other points which were not a primary reason for this PR.

2022-05-30 13:25 UTC, ktrout1111 commented
> With sandwich attacks, there is risk involved with current system as latency is not deterministic - with deterministic txn ordering, sandwich attacks become more viable.

OK, I get you now. The use of the word "deterministic" threw me off. What you are saying is that under sorting by hash, a bot can decide whether a given tx comes before or after a mark, whereas under the current system each tx could occur before or after. The latter fact is then used to argue that sorting by hash increases the viability of sandwich attacks. OK, that sounds reasonable on the surface but surely it's reasonably straightforward to write a contract that automagically detects whether it has landed before or after the mark. It seems a little fiddly, but doable to a reasonable margin of error. This strategy could then work regardless of the tx sorting algorithm.

2022-05-30 13:29 UTC, ktrout1111 commented
> You said it yourself that many nodes are "geographically centralized" so this can be optimized easily (quality beats quantity).

In theory, I'd agree with you, but my practical experiments have not backed this up. I don't fully understand why it is apparently necessary to run hundreds (or at least dozens) of nodes to get the edge, when nearly all nodes are clustered in 10 data centres around the world. It probably has something to do with always needing to have a node in the square root of the nearest dataseed peer. The margins are probably razor thin in most cases (<1ms), but enough to make _all_ the difference. So, whatever the reason is, quantity does matter.

2022-05-30 16:24 UTC, guagualvcha commented
This has been fully discussed in [ethereum/go-ethereum#21350 (comment)](https://github.com/ethereum/go-ethereum/issues/21350) , agree with the statement that: 


```
Hash ordering is not a solution as bots will still spam better hashes as they mine them. They cannot rely on what they see in their local mempool to determine whether they will win with their last submitted hash. 
```

Hash ordering is a deterministic sorting algorithm that makes the winner always win. While P2P connection latency is a more uncontrollable factor,  the randomness of transaction propagation protocol also erodes the geographical advantage. It is fairer for the small fish.

There are two kinds of spam we are talking about here.  1. P2P networking spam: the spam transactions sent by fake nodes; The transaction is sent by the same sender with the same nonce, the txpool will discard the duplicated tx, it won’t cause traffic flooding over the network, seems sustainable so far. 2. Spam transactions within blocks. Random ordering will encourage spam transactions, Receive Time and Hash ordering are better choices in this aspect.

In general, deterministic and totally random sorting algorithms are something we want to avoid, the current implementation is a trade-off.

This PR will affect a lot of arbs and liquidation providers,  no rush decision will be made before we get a very very STRONG reason.

2022-05-30 16:55 UTC, MrSonicMaster commented
> on the surface but surely it's reasonably straightforward to write a contract that automagically detects whether it has landed before or after the mark. It seems a little fiddly, but doable to a reasonable margin of error. This strategy could then work regardless of the tx sorting algorithm.

While that is possible for certain things, sandwich attacks are not atomic. You must frontrun with a buy, then backrun with a sell in 2 separate txns. Since each txn lives in its own VM, it can't know whether or not the other has been successfully executed or was in the correct order. 


> In theory, I'd agree with you, but my practical experiments have not backed this up. I don't fully understand why it is apparently necessary to run hundreds (or at least dozens) of nodes to get the edge, when nearly all nodes are clustered in 10 data centres around the world. It probably has something to do with always needing to have a node in the square root of the nearest dataseed peer. The margins are probably razor thin in most cases (<1ms), but enough to make _all_ the difference. So, whatever the reason is, quantity does matter.

Yes, now that you remind me of the random txn distribution I can see why more connections to the same people can improve latency. I guess it would make sense that, given the time these bot developers have had (and the incentive to stay on top), they will have optimized for any millisecond they can get.

2022-05-30 17:48 UTC, ktrout1111 commented
> While that is possible for certain things, sandwich attacks are not atomic. You must frontrun with a buy, then backrun with a sell in 2 separate txns. Since each txn lives in its own VM, it can't know whether or not the other has been successfully executed or was in the correct order.

I'm aware of this. Each tx can know if its more or after the mark by calling getReserves() on the target pair and comparing against an input value. It can use storage fields of its own contract to record if the front and/or backruns have already taken place. Easy peasy.

2022-05-31 10:32 UTC, MrSonicMaster commented
> I'm aware of this. Each tx can know if its before or after the mark by calling getReserves() on the target pair and comparing against an input value. It can use storage fields of its own contract to record if the front and/or backruns have already taken place. Easy peasy. So even under a scheme where "deterministic" ordering isnt endemic, it can be emulated with little trouble.

This is correct, you can tell during inclusion if you are in a position to execute the buy at equal or better position than the off-chain math was computed with by passing 'reference' value in calldata and using getReserves (slippage tolerance). You submit buy+sell in the same packet, and rely on gas price to order the 'buy' ahead of the target, and rely on latency advantage to get the 'sell' directly after target. But imagine a competitor is 1ms faster than you, but uses a lower but still effective gas price than you for the 'buy' (ex. target is 5gwei, you used 6 gwei, he uses 5.5gwei). Now it will order like this: your buy, his buy, target buy, his sell, your sell. You can not conclude from EVM that his buy was after yours, or that his sell was before yours. You can pull tricks to minimize risk - but no matter the scenario, the current system will imply some form of risk.

2022-06-13 08:41 UTC, closed without merging

2022-06-13 09:19 UTC, lennybakkalian commented
a bit sad that the maintainers did not even address the individual points of criticism (e.g. fake nodes) for such a widely discussed topic.

2022-06-13 09:26 UTC, cwazy2020 commented
> a bit sad that the maintainers did not even address the individual points of criticism (e.g. fake nodes) for such a widely discussed topic.

Any PR like this that would interrupt the flow of profits to the richest people has no chance of being implemented.  I'm sure Binance itself is one of the major competitors running tons of spam nodes, and they aren't going to cost themselves money.  I would have liked to see it happen, but I knew it wouldn't.  I think we all did on some level.  Any explanation they would have made would have been a lie, so instead they just said nothing.