[WIP] fix pipecommit issue
bnb-chain/bsc pull request #932
Opened 2022-05-29 13:24 UTC by forcodedancing

### Description

add a description of your changes here...

### Rationale

tell us why we need these changes...

### Example

add an example CLI or API response...

### Changes

Notable changes: 
* add each change in a bullet point here
* ...

2022-05-31 06:14 UTC, guagualvcha approved these changes

2022-05-31 06:15 UTC, guagualvcha requested changes
It will keep as dummy root?

2022-05-31 06:24 UTC, guagualvcha submitted a review, later dismissed

2022-05-31 08:44 UTC, yutianwu approved these changes

2022-05-31 13:06 UTC, setunapo commented on core/state/statedb.go
> +				if account, exist := accounts[crypto.Keccak256Hash(obj.address[:])]; exist {
This is the only place that changes the behavior, others changes in this PR is just code refine.
But how could `len(account.Root) == 0` ?

2022-05-31 13:08 UTC, setunapo commented
Another suggestion, commit description should add more detail to tell how it is fixed, better to avoid `fix a bug`

2022-05-31 13:09 UTC, setunapo commented
Another suggestion, commit description should add more detail to tell how it is fixed, better to avoid `fix a bug`

2022-05-31 13:23 UTC, forcodedancing commented
> Another suggestion, commit description should add more detail to tell how it is fixed, better to avoid `fix a bug`

sure, let me refine it.

2022-05-31 13:26 UTC, forcodedancing commented
> Another suggestion, commit description should add more detail to tell how it is fixed, better to avoid `fix a bug`

sure, let me refine it.

2022-06-01 09:05 UTC, setunapo submitted a review, later dismissed

2022-06-07 02:17 UTC, yutianwu approved these changes

2022-06-07 02:54 UTC, setunapo approved these changes

2022-06-13 08:40 UTC, guagualvcha approved these changes

2022-06-13 08:40 UTC, merged